"""Emit adapters — compile the ONE canonical workspace into surface-specific files.

The canonical source is context/ + skills/ + frameworks/. Each adapter renders
that into the format a given AI tool understands, written to the tool's expected
location. Adapters are generated, never hand-edited — re-run `wsx emit <target>`.

Agnostic by design: the same workspace targets Claude (recommended), AGENTS.md
(Cursor/Copilot/Codex/Gemini/…), Cursor rules, MCP, or a tool-less context pack.

Privacy: when contexts.personal.private is true (walled), personal context is
NEVER included in emitted output — it stays local.
"""
from __future__ import annotations

import json
from pathlib import Path

from . import core

# context notes included in agnostic emits (personal.md is excluded when walled)
_PUBLIC_CONTEXT = ["project-context.md", "session-log.md", "relational.md"]


def _read(root: Path, rel: str) -> str:
    f = root / rel
    return f.read_text(encoding="utf-8") if f.exists() else ""


def gather(root: Path, profile: dict, include_personal: bool = False):
    """Collect the canonical material for emission."""
    walled = bool(profile.get("contexts", {}).get("personal", {}).get("private", True))
    notes = []
    for rel in _PUBLIC_CONTEXT:
        body = _read(root, f"context/{rel}")
        if body.strip():
            notes.append((rel, body))
    if include_personal and not walled:
        body = _read(root, "context/personal.md")
        if body.strip():
            notes.append(("personal.md", body))
    skills = []
    for name, sk in core.iter_skills(root):
        fm, _body = core.parse_frontmatter(sk)
        skills.append({
            "name": name,
            "description": str(fm.get("description", "")).strip(),
            "triggers": core.skill_triggers(fm),
            "hub": fm.get("hub", ""),
            "path": f"skills/{name}/SKILL.md",
        })
    return {"walled": walled, "notes": notes, "skills": skills}


def _skill_index_md(skills: list) -> str:
    if not skills:
        return "_(no skills yet — the interview + resolver populate these.)_\n"
    out = []
    for s in skills:
        trg = f" — triggers: {', '.join(s['triggers'])}" if s["triggers"] else ""
        hub = f" [{s['hub']}]" if s["hub"] else ""
        out.append(f"- **{s['name']}**{hub} — {s['description'] or '(no description)'}{trg}")
    return "\n".join(out) + "\n"


def _identity(profile: dict) -> str:
    return str(profile.get("identity", {}).get("name", "you"))


def _record(root: Path, manifest: dict, target: str, files: list):
    rel = [str(Path(f).relative_to(root)) for f in files]
    manifest.setdefault("emitted", {})[target] = {"files": rel, "at": core.now_stamp()}
    core.save_manifest(root, manifest)


# --------------------------------------------------------------------- pack ---
def emit_pack(root: Path, profile: dict, manifest: dict) -> list:
    g = gather(root, profile)
    parts = [
        f"# Context Pack — {_identity(profile)}",
        "",
        "_A single, paste-anywhere brief for any AI assistant. Generated by `wsx emit pack`._",
        f"_Separation: {profile.get('lifecycle', {}).get('separation', 'walled')} "
        f"(personal context {'excluded' if g['walled'] else 'included'})._",
        "",
        "## Who you're working with",
        "",
        f"- Name: {_identity(profile)}",
        f"- Role: {profile.get('contexts', {}).get('work', {}).get('role', '') or '(unspecified)'}",
        f"- Preferences: {profile.get('preferences', {}).get('tone', '') or '(unspecified)'}",
        "",
        "## Specialized skills available",
        "",
        _skill_index_md(g["skills"]),
        "## Building new skills — supreme rule",
        "",
        "To add any skill, hub, framework, or playbook, follow the process in this",
        "workspace's `frameworks/skill-authoring.md`: it supersedes native skill-creation —",
        "set the altitude from the person's per-domain expertise, source from skills +",
        "references and cite, reconcile triggers, and pass the acceptance checklist.",
        "",
    ]
    # Token frugality: the pack is meant to be pasted into a chat, so cap each note
    # to its most useful head instead of dumping whole (possibly huge) context files.
    NOTE_CAP = 4000  # chars ≈ 1k tokens per note
    for rel, body in g["notes"]:
        b = body.strip()
        if len(b) > NOTE_CAP:
            b = b[:NOTE_CAP].rstrip() + f"\n\n_…(truncated for token frugality — open `{rel}` for the rest)_"
        parts += [f"## {rel}", "", b, ""]
    out = root / "adapters" / "context-pack.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(parts) + "\n", encoding="utf-8")
    _record(root, manifest, "pack", [out])
    return [out]


# ---------------------------------------------------------------- agents-md ---
def _agents_md_body(root: Path, profile: dict) -> str:
    g = gather(root, profile)
    name = _identity(profile)
    return "\n".join([
        f"# AGENTS.md — {name}'s workspace",
        "",
        "Instructions for any AI coding agent (open standard: https://agents.md).",
        "Generated by `wsx emit agents-md` — do not hand-edit; edit the canonical",
        "workspace (context/, skills/) and re-emit.",
        "",
        "## About",
        f"- Name: {name}",
        f"- Role: {profile.get('contexts', {}).get('work', {}).get('role', '') or '(unspecified)'}",
        f"- Tone/preferences: {profile.get('preferences', {}).get('tone', '') or '(unspecified)'}",
        f"- Separation: {profile.get('lifecycle', {}).get('separation', 'walled')} "
        "(personal context is local-only and not described here).",
        "",
        "## Token frugality — a top priority",
        "This workspace must never cost more tokens than the value it adds. Read the TOP",
        "(most recent) of the context files — never a whole growing log. Load a skill only",
        "when its trigger fires; prefer the smallest sufficient context.",
        "",
        "## Context files (read the head, not the whole file)",
        "- `context/CRITICAL_FACTS.md` — **read this FIRST every session**: the tiny, always-",
        "  loaded hot cache of facts never to re-derive. Everything else is one hop from `HOME.md`.",
        "- `context/project-context.md` — active projects + pending items (skim the top).",
        "- `context/session-log.md` — recent session history; **bounded** (older blocks are",
        "  in `context/session-log-archive.md`, read only on demand).",
        "- `context/decisions/` — ADRs: why the meaningful choices were made (read on demand).",
        "- `context/conventions.md` — note conventions (typed edges, freshness, the preamble).",
        "- `knowledge/` — durable domain insight (patterns, constraints, research). Read the",
        "  index before substantive domain work; propose an entry when a session yields one.",
        "- `projects/<name>/PROJECT.md` — per-project documentation & context (overview, where",
        "  the code lives, live handoff, decisions). Read the relevant one before working on a",
        "  project; the code itself lives in that project's own repo, not in this vault.",
        "- `HOME.md` — the vault's linked front door (index of everything).",
        "",
        "## Note conventions (keep the graph connected + trustworthy)",
        "- **Link generously** with `[[wikilinks]]`; for typed relationships use a `relations:`",
        "  front-matter block (`builds-on`/`relates-to`/`contradicts`/`refutes`/`exemplifies`).",
        "- **Freshness:** every claim is *timeless* (a principle), *dated* (`as of YYYY-MM`), or",
        "  a *pointer* (link to a live source). Tag anything past its horizon `#stale`.",
        "- **Open durable notes with a `## For future agent`** block (TL;DR + key claims + as-of).",
        "- Record a real choice as an ADR in `context/decisions/` (copy `_TEMPLATE.md`).",
        "- Run `wsx health` to catch orphans, stale claims, and dangling typed edges.",
        "",
        "## Session end (multi-device safe)",
        "Record your session as a **fragment**: write your block to",
        "`context/sessions/{date}-{short-id}.md` with a `SessionID:` line (never edit the",
        "shared `session-log.md`), then run `wsx compact` and `wsx sync`. Disjoint fragment",
        "files never collide across devices/sessions/surfaces.",
        "",
        "## Specialized skills",
        _skill_index_md(g["skills"]),
        "## Building skills, hubs, frameworks, or playbooks — SUPREME RULE",
        "When asked to build/add any skill, hub, framework, or playbook, follow",
        "`frameworks/skill-authoring.md` — it SUPERSEDES any native skill-creation. Set the",
        "altitude from the person's per-domain level (`profile.yaml` → `expertise`), source from",
        "skills + references and cite, reconcile triggers, and pass the acceptance checklist.",
        "",
        "## Conventions",
        "- Respect the privacy wall: never read or surface `context/personal.md`.",
        "- Keep changes small and verified.",
    ]) + "\n"


def emit_agents_md(root: Path, profile: dict, manifest: dict) -> list:
    out = root / "AGENTS.md"
    out.write_text(_agents_md_body(root, profile), encoding="utf-8")
    _record(root, manifest, "agents-md", [out])
    return [out]


# -------------------------------------------------------------- claude-code ---
def emit_claude_code(root: Path, profile: dict, manifest: dict) -> list:
    g = gather(root, profile)
    name = _identity(profile)
    written = []

    claude_md = "\n".join([
        f"# {name}'s Workspace — Claude instructions",
        "",
        "_Generated by `wsx emit claude-code`. Canonical source: context/ + skills/._",
        "",
        "## Token frugality — a top priority",
        "This workspace must never cost the person MORE tokens than the value it adds.",
        "Read **frugally**: the TOP (most recent) of `context/project-context.md` and",
        "`context/session-log.md` is enough to orient — do NOT read whole logs. Older",
        "history lives in `session-log-archive.md`; open it only if a task truly needs it.",
        "Load a skill only when its trigger fires; prefer the smallest sufficient context.",
        "",
        "## Session start & end (multi-device safe)",
        "At session start, read `context/CRITICAL_FACTS.md` FIRST (the tiny always-on hot",
        "cache), then skim the top of `context/project-context.md` and `context/session-log.md`",
        "for the active work. Respect the privacy wall: never read `context/personal.md`",
        "unless explicitly asked.",
        "At session **end**, record what happened as a **fragment** — write your Session",
        "Block to `context/sessions/{date}-{short-id}.md` with a `SessionID:` line (never",
        "edit the shared `session-log.md` directly), then run `wsx compact` to fold it in",
        "and `wsx sync` to push. Disjoint fragment files never collide across your devices.",
        "",
        "## Projects (per-project documentation)",
        "Each project has a docs folder at `projects/<name>/PROJECT.md` (overview, where the",
        "code lives, live handoff, decisions) — read the relevant one before working on that",
        "project. The code and assets live in the project's own repo, not this vault. Start",
        "any browse from `HOME.md`, the linked front door.",
        "",
        "## Note conventions",
        "Keep the vault a connected, trustworthy graph: link with `[[wikilinks]]` (typed",
        "`relations:` for builds-on/refutes/etc.); mark every claim *timeless* / *dated*",
        "(`as of YYYY-MM`) / *pointer* and tag stale ones `#stale`; open durable notes with a",
        "`## For future agent` block; record real choices as ADRs in `context/decisions/`.",
        "See `context/conventions.md`; run `wsx health` to catch orphans + drift.",
        "",
        "## Preferences",
        f"- Tone: {profile.get('preferences', {}).get('tone', '') or '(unspecified)'}",
        f"- Audience: {profile.get('preferences', {}).get('audience', '') or '(unspecified)'}",
        "",
        "## Building skills, hubs, frameworks, or playbooks — SUPREME RULE",
        "When asked to build/add/create any skill, hub, spoke, framework, or playbook,",
        "**follow `frameworks/skill-authoring.md` — it SUPERSEDES your native skill-creation.**",
        "Set the altitude from the person's per-domain level (`profile.yaml` → `expertise`),",
        "source from skills + references and cite, reconcile triggers, and pass the acceptance",
        "checklist before calling it done. Do not use a built-in skill-builder instead.",
        "",
        "## Skills (load on demand)",
        _skill_index_md(g["skills"]),
    ]) + "\n"
    cm = root / "CLAUDE.md"
    cm.write_text(claude_md, encoding="utf-8")
    written.append(cm)

    # Hooks make context loading GUARANTEED rather than advisory. Without them the AI
    # only reads CRITICAL_FACTS if it chooses to obey CLAUDE.md; with them the harness
    # injects it every session. Read-only + local by design (see the script's header).
    hook = root / ".claude" / "hooks" / "session-start.py"
    hook.parent.mkdir(parents=True, exist_ok=True)
    hook.write_text(_SESSION_START_HOOK, encoding="utf-8")
    hook.chmod(0o755)
    written.append(hook)

    settings = root / ".claude" / "settings.json"
    # Merge, never clobber: the person may have their own settings/hooks here.
    existing = {}
    if settings.exists():
        try:
            existing = json.loads(settings.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            existing = {}
    # `python3` alone dead-ends on Windows (it's `python` / the `py` launcher there), and
    # a workspace syncs across machines — so the command must degrade. `||` is honoured by
    # both POSIX shells and cmd.exe, so the first interpreter that exists wins.
    _h = "\"$CLAUDE_PROJECT_DIR/.claude/hooks/session-start.py\""
    cmd = f"python3 {_h} || python {_h}"
    hooks_cfg = existing.setdefault("hooks", {})
    entries = hooks_cfg.get("SessionStart", [])

    # Drop every entry that invokes OUR hook, then add exactly one back. Matching on a
    # substring of json.dumps() does NOT work (it escapes the quotes in the command), so
    # an earlier version appended a duplicate on every emit and the hook fired N times.
    # Rebuilding structurally is idempotent AND self-heals workspaces that accumulated
    # duplicates. Entries the person added themselves are preserved untouched.
    def _is_ours(entry):
        if not isinstance(entry, dict):
            return False
        for h in entry.get("hooks", []) or []:
            if isinstance(h, dict) and "session-start.py" in str(h.get("command", "")):
                return True
        return False

    kept_entries = [e for e in entries if not _is_ours(e)]
    kept_entries.append({"hooks": [{"type": "command", "command": cmd}]})
    hooks_cfg["SessionStart"] = kept_entries
    settings.write_text(json.dumps(existing, indent=2) + "\n", encoding="utf-8")
    written.append(settings)

    # A self-repair skill, so the person never needs a command line. Opening THIS folder
    # and saying "update my workspace" is enough — the assistant drives the vendored CLI.
    maint = root / ".claude" / "skills" / "workspace-maintenance" / "SKILL.md"
    maint.parent.mkdir(parents=True, exist_ok=True)
    maint.write_text(_MAINTENANCE_SKILL, encoding="utf-8")
    written.append(maint)

    # mirror skills into .claude/skills/<name>/SKILL.md so Claude Code discovers them.
    # A pulled skill stays byte-identical to its pin on disk; its owner's deltas live
    # in a sibling overlay.md, so we compose (pulled base + overlay) into the mirror —
    # never back into the read-only source.
    for name_, sk in core.iter_skills(root):
        text = sk.read_text(encoding="utf-8")
        overlay = sk.parent / "overlay.md"
        if overlay.exists():
            _, ov_body = core.parse_frontmatter(overlay)
            text = f"{text.rstrip()}\n\n---\n\n## House overlay (your deltas)\n\n{ov_body.strip()}\n"
        dst = root / ".claude" / "skills" / name_ / "SKILL.md"
        dst.parent.mkdir(parents=True, exist_ok=True)
        dst.write_text(text, encoding="utf-8")
        written.append(dst)

    _record(root, manifest, "claude-code", written)
    return written


_SESSION_START_HOOK = '''#!/usr/bin/env python3
"""SessionStart hook — inject this workspace's hot context at the top of every session.

WHAT IT DOES: reads a few local markdown files and prints them, so the assistant starts
with your critical facts and current work instead of a cold context.

WHAT IT DOES NOT DO: it makes no network calls, writes nothing, runs nothing else, and
NEVER reads `context/personal.md` (the walled private note). It is read-only and local.
Delete `.claude/settings.json` (or this file) to turn it off.

Token-frugal on purpose: the hot cache in full, then only the HEAD of the growing logs.
"""
import sys
from pathlib import Path

WS = Path(__file__).resolve().parents[2]
HEAD_LINES = 40          # never dump a whole growing log


def head(rel, n=HEAD_LINES, whole=False):
    f = WS / rel
    if not f.exists():
        return ""
    try:
        text = f.read_text(encoding="utf-8")
    except OSError:
        return ""
    if whole:
        return text.strip()
    lines = text.splitlines()
    out = "\\n".join(lines[:n]).strip()
    if len(lines) > n:
        out += f"\\n\\n_…(head only — open `{rel}` for the rest)_"
    return out


def main():
    parts = ["# Workspace context (auto-loaded)", ""]
    crit = head("context/CRITICAL_FACTS.md", whole=True)
    if crit:
        parts += ["## Critical facts — never re-derive these", "", crit, ""]
    proj = head("context/project-context.md")
    if proj:
        parts += ["## Current work (head of project-context.md)", "", proj, ""]
    log = head("context/session-log.md", n=25)
    if log:
        parts += ["## Recent sessions (head)", "", log, ""]
    parts += [
        "## Standing rules",
        "- Read frugally: heads of logs, not whole files. Load a skill only when its trigger fires.",
        "- Privacy wall: never read `context/personal.md` unless explicitly asked.",
        "- Start any browse from `HOME.md`. Adapters (`AGENTS.md`, `CLAUDE.md`, `_INDEX.md`)",
        "  are GENERATED — edit the canonical source and re-run `wsx emit`.",
        "- Record a real choice as an ADR in `context/decisions/`; a durable insight in `knowledge/`.",
        "",
    ]
    sys.stdout.write("\\n".join(parts))
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''


_MAINTENANCE_SKILL = '''---
name: workspace-maintenance
description: >-
  Repair, update, or health-check THIS workspace. Use whenever the person says
  "update my workspace", "upgrade my workspace", "fix my workspace", "something's
  wrong with my workspace", "check my workspace", "is my workspace set up right",
  or reports that files/links/settings look stale or contradictory. Drives the
  workspace's own vendored `wsx` CLI — the person never needs a command line.
triggers:
  - update my workspace
  - upgrade my workspace
  - fix my workspace
  - check my workspace
  - workspace health
  - something is wrong with my workspace
---

# Workspace maintenance — you drive the tools, not the person

This workspace ships its own CLI at `wsx.py` (vendored under `.wsx/`), so everything
below runs **here**, with no install and no PATH setup. **Run these yourself** — the
person should never be asked to open a terminal or paste a command.

## The repair pass (run in this order)

```bash
python3 wsx.py doctor            # environment: python, git, git identity
python3 wsx.py upgrade           # add missing pieces, repair stale generated content, first commit
python3 wsx.py emit all          # recompile the AI adapter files from the canonical source
python3 wsx.py health            # orphan notes, #stale/aging claims, dangling typed edges
python3 wsx.py lint              # skills: unfilled skeletons, trigger overlaps
```

`upgrade` is **non-destructive** — it never overwrites anything the person wrote. It adds
missing scaffold, regenerates the derived layer (HOME, indexes, `context/profile.md`),
repairs known-stale generated lines, and lands a first git commit if the repo has none.

## Then interpret the output for them, in plain language

Report **what changed and what it means**, not raw tool output. Specifically:

- **`doctor` or `upgrade` says git identity is not set** → this is why nothing is being
  saved to history. Ask them: *"What name and email should your saved work be signed
  with?"* then run it **for them**:
  `python3 wsx.py identity --name "…" --email "…"`
  That sets it for this workspace only (not their global git config) and makes the first
  commit. If they don't want a personal address in public commits, suggest their GitHub
  noreply address (Settings → Emails → *Keep my email private*).
- **`health` lists orphan notes** → offer to link each from its natural parent, or archive
  it. Never delete.
- **`health`/`lint` flag stale or unfinished content** → offer to fix; get a yes first.
- **No git remote yet** → `python3 wsx.py remote` explains the free options; they create the
  empty repo, you wire it with `python3 wsx.py remote <url>` then `python3 wsx.py sync`.

## Ground rules

- Never ask the person to run a command. You have the tools; use them.
- Never read `context/personal.md` unless they explicitly ask.
- The canonical source is `context/` + `skills/`; files under `adapters/`, `AGENTS.md`,
  `CLAUDE.md`, `HOME.md`, and the `_INDEX.md` files are **generated** — fix the source and
  re-run `emit`, never hand-edit the output.
'''


# ------------------------------------------------------------------- cursor ---
def emit_cursor(root: Path, profile: dict, manifest: dict) -> list:
    written = []
    rule = root / ".cursor" / "rules" / "00-workspace.mdc"
    rule.parent.mkdir(parents=True, exist_ok=True)
    g = gather(root, profile)
    body = "\n".join([
        "---",
        "description: Personal workspace context + skills",
        "alwaysApply: true",
        "---",
        "",
        f"# {_identity(profile)}'s workspace",
        "",
        "Token frugality is a top priority: skim the TOP of `context/project-context.md`",
        "and `context/session-log.md` (bounded; history in `session-log-archive.md` on demand)",
        "— never read a whole growing log. Load a skill only when its trigger fires.",
        "Record sessions as fragments in `context/sessions/` then `wsx compact`.",
        "Never read `context/personal.md` (private, walled).",
        "",
        "To build any skill/hub/framework/playbook, follow `frameworks/skill-authoring.md`",
        "(SUPERSEDES native skill-creation): altitude from per-domain expertise, source +",
        "cite, reconcile triggers, pass the acceptance checklist.",
        "",
        "## Skills",
        _skill_index_md(g["skills"]),
    ]) + "\n"
    rule.write_text(body, encoding="utf-8")
    written.append(rule)
    # Cursor also reads AGENTS.md — emit it too for a complete agnostic setup.
    written += emit_agents_md(root, profile, manifest)
    _record(root, manifest, "cursor", written)
    return written


# ---------------------------------------------------------------------- mcp ---
def emit_mcp(root: Path, profile: dict, manifest: dict) -> list:
    """Emit the universal runtime: a self-contained, zero-dep stdio MCP server that
    serves the live workspace (context/, skills/, manifest.json) to any MCP client.
    One server lights up Cursor + Codex + Claude Desktop + local frontends (SPEC §5).
    """
    from . import mcp_template

    out_dir = root / "adapters" / "mcp"
    out_dir.mkdir(parents=True, exist_ok=True)
    written = []

    server = out_dir / "server.py"
    server.write_text(mcp_template.SERVER_PY, encoding="utf-8")
    server.chmod(0o755)
    written.append(server)

    # copy-paste client config, with the absolute path already filled in
    cfg = out_dir / "mcp.json"
    config = {
        "mcpServers": {
            "workspace": {
                "command": "python3",
                "args": [str(server.resolve())],
                "env": {},
            }
        }
    }
    cfg.write_text(json.dumps(config, indent=2) + "\n", encoding="utf-8")
    written.append(cfg)

    readme = out_dir / "README.md"
    readme.write_text(_mcp_readme(server), encoding="utf-8")
    written.append(readme)

    _record(root, manifest, "mcp", written)
    return written


def _mcp_readme(server: Path) -> str:
    return "\n".join([
        "# workspace-mcp — the universal runtime",
        "",
        "_Generated by `wsx emit mcp`. A zero-dependency (stdlib-only) MCP server that",
        "serves this workspace to any MCP client over stdio. One server, many frontends._",
        "",
        "## Tools",
        "",
        "- **context_load** — load canonical context (profile, project-context, session-log).",
        "  Personal context is walled: excluded unless `include_personal: true`.",
        "- **skills_search** — search the skill network by name, hub, or trigger.",
        "- **skills_load** — load a skill's full `SKILL.md` (overlays composed in).",
        "- **session_start** — boot summary + context.",
        "- **session_end** — append a session block to the log.",
        "- **reconcile** — cross-machine reconcile (CLI-only for now).",
        "",
        "## Register it",
        "",
        "The generated `mcp.json` already has the absolute path filled in. Point your",
        "client at it:",
        "",
        "- **Claude Desktop** — merge `mcp.json`'s `mcpServers` into",
        "  `~/Library/Application Support/Claude/claude_desktop_config.json` (macOS).",
        "- **Cursor** — add the same block to `.cursor/mcp.json` or your global Cursor MCP config.",
        "- **Any MCP client** — run `python3 " + server.name + "` as a stdio server from this dir.",
        "",
        "The server finds this workspace from its own path; override with the",
        "`WSX_WORKSPACE` environment variable if you relocate it.",
        "",
        "## Degradation ladder",
        "",
        "MCP (this) → the `wsx` CLI → a pasteable context pack (`wsx emit pack`). Each rung",
        "works without the one above it.",
        "",
    ])


ADAPTERS = {
    "pack": emit_pack,
    "agents-md": emit_agents_md,
    "claude-code": emit_claude_code,
    "cursor": emit_cursor,
    "mcp": emit_mcp,
}


def emit(root: Path, target: str, profile: dict, manifest: dict) -> list:
    if target == "all":
        from . import moc
        written = []
        for name in ("claude-code", "agents-md", "cursor", "pack", "mcp"):
            written += ADAPTERS[name](root, profile, manifest)
        # Refresh the connective MOC layer so the vault graph reflects current skills.
        written += moc.write_mocs(root)
        return written
    if target not in ADAPTERS:
        raise SystemExit(
            f"error: unknown emit target '{target}'. "
            f"choose: {', '.join(ADAPTERS)} | all"
        )
    return ADAPTERS[target](root, profile, manifest)
