"""Emit adapters — compile the ONE canonical workspace into surface-specific files.

The canonical source is context/ + skills/ + frameworks/. Each adapter renders
that into the format a given AI tool understands, written to the tool's expected
location. Adapters are generated, never hand-edited — re-run `wsx emit <target>`.

Agnostic by design: the same workspace targets Claude (recommended), AGENTS.md
(Cursor/Copilot/Codex/Gemini/…), Cursor rules, MCP, or a tool-less context pack.

Privacy: when contexts.personal.private is true (walled), personal context is
NEVER included in emitted output — it stays local.
"""
from __future__ import annotations

import json
from pathlib import Path

from . import core

# context notes included in agnostic emits (personal.md is excluded when walled)
_PUBLIC_CONTEXT = ["project-context.md", "session-log.md", "relational.md"]


def _read(root: Path, rel: str) -> str:
    f = root / rel
    return f.read_text(encoding="utf-8") if f.exists() else ""


def gather(root: Path, profile: dict, include_personal: bool = False):
    """Collect the canonical material for emission."""
    walled = bool(profile.get("contexts", {}).get("personal", {}).get("private", True))
    notes = []
    for rel in _PUBLIC_CONTEXT:
        body = _read(root, f"context/{rel}")
        if body.strip():
            notes.append((rel, body))
    if include_personal and not walled:
        body = _read(root, "context/personal.md")
        if body.strip():
            notes.append(("personal.md", body))
    skills = []
    for name, sk in core.iter_skills(root):
        fm, _body = core.parse_frontmatter(sk)
        skills.append({
            "name": name,
            "description": str(fm.get("description", "")).strip(),
            "triggers": core.skill_triggers(fm),
            "hub": fm.get("hub", ""),
            "path": f"skills/{name}/SKILL.md",
        })
    return {"walled": walled, "notes": notes, "skills": skills}


def _skill_index_md(skills: list) -> str:
    if not skills:
        return "_(no skills yet — the interview + resolver populate these.)_\n"
    out = []
    for s in skills:
        trg = f" — triggers: {', '.join(s['triggers'])}" if s["triggers"] else ""
        hub = f" [{s['hub']}]" if s["hub"] else ""
        out.append(f"- **{s['name']}**{hub} — {s['description'] or '(no description)'}{trg}")
    return "\n".join(out) + "\n"


def _identity(profile: dict) -> str:
    return str(profile.get("identity", {}).get("name", "you"))


def _record(root: Path, manifest: dict, target: str, files: list):
    rel = [str(Path(f).relative_to(root)) for f in files]
    manifest.setdefault("emitted", {})[target] = {"files": rel, "at": core.now_stamp()}
    core.save_manifest(root, manifest)


# --------------------------------------------------------------------- pack ---
def emit_pack(root: Path, profile: dict, manifest: dict) -> list:
    g = gather(root, profile)
    parts = [
        f"# Context Pack — {_identity(profile)}",
        "",
        "_A single, paste-anywhere brief for any AI assistant. Generated by `wsx emit pack`._",
        f"_Separation: {profile.get('lifecycle', {}).get('separation', 'walled')} "
        f"(personal context {'excluded' if g['walled'] else 'included'})._",
        "",
        "## Who you're working with",
        "",
        f"- Name: {_identity(profile)}",
        f"- Role: {profile.get('contexts', {}).get('work', {}).get('role', '') or '(unspecified)'}",
        f"- Preferences: {profile.get('preferences', {}).get('tone', '') or '(unspecified)'}",
        "",
        "## Specialized skills available",
        "",
        _skill_index_md(g["skills"]),
        "## Building new skills — supreme rule",
        "",
        "To add any skill, hub, framework, or playbook, follow the process in this",
        "workspace's `frameworks/skill-authoring.md`: it supersedes native skill-creation —",
        "set the altitude from the person's per-domain expertise, source from skills +",
        "references and cite, reconcile triggers, and pass the acceptance checklist.",
        "",
    ]
    # Token frugality: the pack is meant to be pasted into a chat, so cap each note
    # to its most useful head instead of dumping whole (possibly huge) context files.
    NOTE_CAP = 4000  # chars ≈ 1k tokens per note
    for rel, body in g["notes"]:
        b = body.strip()
        if len(b) > NOTE_CAP:
            b = b[:NOTE_CAP].rstrip() + f"\n\n_…(truncated for token frugality — open `{rel}` for the rest)_"
        parts += [f"## {rel}", "", b, ""]
    out = root / "adapters" / "context-pack.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(parts) + "\n", encoding="utf-8")
    _record(root, manifest, "pack", [out])
    return [out]


# ---------------------------------------------------------------- agents-md ---
def _agents_md_body(root: Path, profile: dict) -> str:
    g = gather(root, profile)
    name = _identity(profile)
    return "\n".join([
        f"# AGENTS.md — {name}'s workspace",
        "",
        "Instructions for any AI coding agent (open standard: https://agents.md).",
        "Generated by `wsx emit agents-md` — do not hand-edit; edit the canonical",
        "workspace (context/, skills/) and re-emit.",
        "",
        "## About",
        f"- Name: {name}",
        f"- Role: {profile.get('contexts', {}).get('work', {}).get('role', '') or '(unspecified)'}",
        f"- Tone/preferences: {profile.get('preferences', {}).get('tone', '') or '(unspecified)'}",
        f"- Separation: {profile.get('lifecycle', {}).get('separation', 'walled')} "
        "(personal context is local-only and not described here).",
        "",
        "## Token frugality — a top priority",
        "This workspace must never cost more tokens than the value it adds. Read the TOP",
        "(most recent) of the context files — never a whole growing log. Load a skill only",
        "when its trigger fires; prefer the smallest sufficient context.",
        "",
        "## Context files (read the head, not the whole file)",
        "- `context/CRITICAL_FACTS.md` — **read this FIRST every session**: the tiny, always-",
        "  loaded hot cache of facts never to re-derive. Everything else is one hop from `HOME.md`.",
        "- `context/project-context.md` — active projects + pending items (skim the top).",
        "- `context/session-log.md` — recent session history; **bounded** (older blocks are",
        "  in `context/session-log-archive.md`, read only on demand).",
        "- `context/decisions/` — ADRs: why the meaningful choices were made (read on demand).",
        "- `context/conventions.md` — note conventions (typed edges, freshness, the preamble).",
        "- `projects/<name>/PROJECT.md` — per-project documentation & context (overview, where",
        "  the code lives, live handoff, decisions). Read the relevant one before working on a",
        "  project; the code itself lives in that project's own repo, not in this vault.",
        "- `HOME.md` — the vault's linked front door (index of everything).",
        "",
        "## Note conventions (keep the graph connected + trustworthy)",
        "- **Link generously** with `[[wikilinks]]`; for typed relationships use a `relations:`",
        "  front-matter block (`builds-on`/`relates-to`/`contradicts`/`refutes`/`exemplifies`).",
        "- **Freshness:** every claim is *timeless* (a principle), *dated* (`as of YYYY-MM`), or",
        "  a *pointer* (link to a live source). Tag anything past its horizon `#stale`.",
        "- **Open durable notes with a `## For future agent`** block (TL;DR + key claims + as-of).",
        "- Record a real choice as an ADR in `context/decisions/` (copy `_TEMPLATE.md`).",
        "- Run `wsx health` to catch orphans, stale claims, and dangling typed edges.",
        "",
        "## Session end (multi-device safe)",
        "Record your session as a **fragment**: write your block to",
        "`context/sessions/{date}-{short-id}.md` with a `SessionID:` line (never edit the",
        "shared `session-log.md`), then run `wsx compact` and `wsx sync`. Disjoint fragment",
        "files never collide across devices/sessions/surfaces.",
        "",
        "## Specialized skills",
        _skill_index_md(g["skills"]),
        "## Building skills, hubs, frameworks, or playbooks — SUPREME RULE",
        "When asked to build/add any skill, hub, framework, or playbook, follow",
        "`frameworks/skill-authoring.md` — it SUPERSEDES any native skill-creation. Set the",
        "altitude from the person's per-domain level (`profile.yaml` → `expertise`), source from",
        "skills + references and cite, reconcile triggers, and pass the acceptance checklist.",
        "",
        "## Conventions",
        "- Respect the privacy wall: never read or surface `context/personal.md`.",
        "- Keep changes small and verified.",
    ]) + "\n"


def emit_agents_md(root: Path, profile: dict, manifest: dict) -> list:
    out = root / "AGENTS.md"
    out.write_text(_agents_md_body(root, profile), encoding="utf-8")
    _record(root, manifest, "agents-md", [out])
    return [out]


# -------------------------------------------------------------- claude-code ---
def emit_claude_code(root: Path, profile: dict, manifest: dict) -> list:
    g = gather(root, profile)
    name = _identity(profile)
    written = []

    claude_md = "\n".join([
        f"# {name}'s Workspace — Claude instructions",
        "",
        "_Generated by `wsx emit claude-code`. Canonical source: context/ + skills/._",
        "",
        "## Token frugality — a top priority",
        "This workspace must never cost the person MORE tokens than the value it adds.",
        "Read **frugally**: the TOP (most recent) of `context/project-context.md` and",
        "`context/session-log.md` is enough to orient — do NOT read whole logs. Older",
        "history lives in `session-log-archive.md`; open it only if a task truly needs it.",
        "Load a skill only when its trigger fires; prefer the smallest sufficient context.",
        "",
        "## Session start & end (multi-device safe)",
        "At session start, read `context/CRITICAL_FACTS.md` FIRST (the tiny always-on hot",
        "cache), then skim the top of `context/project-context.md` and `context/session-log.md`",
        "for the active work. Respect the privacy wall: never read `context/personal.md`",
        "unless explicitly asked.",
        "At session **end**, record what happened as a **fragment** — write your Session",
        "Block to `context/sessions/{date}-{short-id}.md` with a `SessionID:` line (never",
        "edit the shared `session-log.md` directly), then run `wsx compact` to fold it in",
        "and `wsx sync` to push. Disjoint fragment files never collide across your devices.",
        "",
        "## Projects (per-project documentation)",
        "Each project has a docs folder at `projects/<name>/PROJECT.md` (overview, where the",
        "code lives, live handoff, decisions) — read the relevant one before working on that",
        "project. The code and assets live in the project's own repo, not this vault. Start",
        "any browse from `HOME.md`, the linked front door.",
        "",
        "## Note conventions",
        "Keep the vault a connected, trustworthy graph: link with `[[wikilinks]]` (typed",
        "`relations:` for builds-on/refutes/etc.); mark every claim *timeless* / *dated*",
        "(`as of YYYY-MM`) / *pointer* and tag stale ones `#stale`; open durable notes with a",
        "`## For future agent` block; record real choices as ADRs in `context/decisions/`.",
        "See `context/conventions.md`; run `wsx health` to catch orphans + drift.",
        "",
        "## Preferences",
        f"- Tone: {profile.get('preferences', {}).get('tone', '') or '(unspecified)'}",
        f"- Audience: {profile.get('preferences', {}).get('audience', '') or '(unspecified)'}",
        "",
        "## Building skills, hubs, frameworks, or playbooks — SUPREME RULE",
        "When asked to build/add/create any skill, hub, spoke, framework, or playbook,",
        "**follow `frameworks/skill-authoring.md` — it SUPERSEDES your native skill-creation.**",
        "Set the altitude from the person's per-domain level (`profile.yaml` → `expertise`),",
        "source from skills + references and cite, reconcile triggers, and pass the acceptance",
        "checklist before calling it done. Do not use a built-in skill-builder instead.",
        "",
        "## Skills (load on demand)",
        _skill_index_md(g["skills"]),
    ]) + "\n"
    cm = root / "CLAUDE.md"
    cm.write_text(claude_md, encoding="utf-8")
    written.append(cm)

    # mirror skills into .claude/skills/<name>/SKILL.md so Claude Code discovers them.
    # A pulled skill stays byte-identical to its pin on disk; its owner's deltas live
    # in a sibling overlay.md, so we compose (pulled base + overlay) into the mirror —
    # never back into the read-only source.
    for name_, sk in core.iter_skills(root):
        text = sk.read_text(encoding="utf-8")
        overlay = sk.parent / "overlay.md"
        if overlay.exists():
            _, ov_body = core.parse_frontmatter(overlay)
            text = f"{text.rstrip()}\n\n---\n\n## House overlay (your deltas)\n\n{ov_body.strip()}\n"
        dst = root / ".claude" / "skills" / name_ / "SKILL.md"
        dst.parent.mkdir(parents=True, exist_ok=True)
        dst.write_text(text, encoding="utf-8")
        written.append(dst)

    _record(root, manifest, "claude-code", written)
    return written


# ------------------------------------------------------------------- cursor ---
def emit_cursor(root: Path, profile: dict, manifest: dict) -> list:
    written = []
    rule = root / ".cursor" / "rules" / "00-workspace.mdc"
    rule.parent.mkdir(parents=True, exist_ok=True)
    g = gather(root, profile)
    body = "\n".join([
        "---",
        "description: Personal workspace context + skills",
        "alwaysApply: true",
        "---",
        "",
        f"# {_identity(profile)}'s workspace",
        "",
        "Token frugality is a top priority: skim the TOP of `context/project-context.md`",
        "and `context/session-log.md` (bounded; history in `session-log-archive.md` on demand)",
        "— never read a whole growing log. Load a skill only when its trigger fires.",
        "Record sessions as fragments in `context/sessions/` then `wsx compact`.",
        "Never read `context/personal.md` (private, walled).",
        "",
        "To build any skill/hub/framework/playbook, follow `frameworks/skill-authoring.md`",
        "(SUPERSEDES native skill-creation): altitude from per-domain expertise, source +",
        "cite, reconcile triggers, pass the acceptance checklist.",
        "",
        "## Skills",
        _skill_index_md(g["skills"]),
    ]) + "\n"
    rule.write_text(body, encoding="utf-8")
    written.append(rule)
    # Cursor also reads AGENTS.md — emit it too for a complete agnostic setup.
    written += emit_agents_md(root, profile, manifest)
    _record(root, manifest, "cursor", written)
    return written


# ---------------------------------------------------------------------- mcp ---
def emit_mcp(root: Path, profile: dict, manifest: dict) -> list:
    """Emit the universal runtime: a self-contained, zero-dep stdio MCP server that
    serves the live workspace (context/, skills/, manifest.json) to any MCP client.
    One server lights up Cursor + Codex + Claude Desktop + local frontends (SPEC §5).
    """
    from . import mcp_template

    out_dir = root / "adapters" / "mcp"
    out_dir.mkdir(parents=True, exist_ok=True)
    written = []

    server = out_dir / "server.py"
    server.write_text(mcp_template.SERVER_PY, encoding="utf-8")
    server.chmod(0o755)
    written.append(server)

    # copy-paste client config, with the absolute path already filled in
    cfg = out_dir / "mcp.json"
    config = {
        "mcpServers": {
            "workspace": {
                "command": "python3",
                "args": [str(server.resolve())],
                "env": {},
            }
        }
    }
    cfg.write_text(json.dumps(config, indent=2) + "\n", encoding="utf-8")
    written.append(cfg)

    readme = out_dir / "README.md"
    readme.write_text(_mcp_readme(server), encoding="utf-8")
    written.append(readme)

    _record(root, manifest, "mcp", written)
    return written


def _mcp_readme(server: Path) -> str:
    return "\n".join([
        "# workspace-mcp — the universal runtime",
        "",
        "_Generated by `wsx emit mcp`. A zero-dependency (stdlib-only) MCP server that",
        "serves this workspace to any MCP client over stdio. One server, many frontends._",
        "",
        "## Tools",
        "",
        "- **context_load** — load canonical context (profile, project-context, session-log).",
        "  Personal context is walled: excluded unless `include_personal: true`.",
        "- **skills_search** — search the skill network by name, hub, or trigger.",
        "- **skills_load** — load a skill's full `SKILL.md` (overlays composed in).",
        "- **session_start** — boot summary + context.",
        "- **session_end** — append a session block to the log.",
        "- **reconcile** — cross-machine reconcile (CLI-only for now).",
        "",
        "## Register it",
        "",
        "The generated `mcp.json` already has the absolute path filled in. Point your",
        "client at it:",
        "",
        "- **Claude Desktop** — merge `mcp.json`'s `mcpServers` into",
        "  `~/Library/Application Support/Claude/claude_desktop_config.json` (macOS).",
        "- **Cursor** — add the same block to `.cursor/mcp.json` or your global Cursor MCP config.",
        "- **Any MCP client** — run `python3 " + server.name + "` as a stdio server from this dir.",
        "",
        "The server finds this workspace from its own path; override with the",
        "`WSX_WORKSPACE` environment variable if you relocate it.",
        "",
        "## Degradation ladder",
        "",
        "MCP (this) → the `wsx` CLI → a pasteable context pack (`wsx emit pack`). Each rung",
        "works without the one above it.",
        "",
    ])


ADAPTERS = {
    "pack": emit_pack,
    "agents-md": emit_agents_md,
    "claude-code": emit_claude_code,
    "cursor": emit_cursor,
    "mcp": emit_mcp,
}


def emit(root: Path, target: str, profile: dict, manifest: dict) -> list:
    if target == "all":
        from . import moc
        written = []
        for name in ("claude-code", "agents-md", "cursor", "pack", "mcp"):
            written += ADAPTERS[name](root, profile, manifest)
        # Refresh the connective MOC layer so the vault graph reflects current skills.
        written += moc.write_mocs(root)
        return written
    if target not in ADAPTERS:
        raise SystemExit(
            f"error: unknown emit target '{target}'. "
            f"choose: {', '.join(ADAPTERS)} | all"
        )
    return ADAPTERS[target](root, profile, manifest)
