"""Command cheat sheet — ONE source of truth for `wsx help` and the emitted COMMANDS.md.

The generated workspace ships a self-contained copy of this CLI under `.wsx/` (+ a `wsx.py`
launcher and `wsx.cmd` for Windows), so **every command below runs from the workspace with
no install and no generator present** — that is the contract this cheat sheet documents.
The command form is `python3 wsx.py <cmd>` (the launcher), which works on every machine the
workspace syncs to.
"""
from __future__ import annotations

from pathlib import Path

# (section, [(command, one-line what-it-does)]). Curated for a human OR an LLM deciding
# what to run — kept in sync with the CLI surface (cli.py) by hand; it is a stable surface.
GROUPS = [
    ("Everyday", [
        ("python3 wsx.py doctor", "where am I · is my setup healthy · what to run next"),
        ("python3 wsx.py emit all", "recompile the AI adapters (CLAUDE.md, AGENTS.md, hooks, MCP, indexes)"),
        ("python3 wsx.py health", "graph hygiene: orphan notes, stale/aging claims, dangling typed edges"),
        ("python3 wsx.py verify", "integrity: profile round-trips + every adapter is emit-ready"),
        ("python3 wsx.py lint", "skills: unfilled skeletons + trigger overlaps"),
        ("python3 wsx.py sync", "save your work: pull --rebase, commit, push"),
    ]),
    ("Session & memory", [
        ("python3 wsx.py session end --summary \"…\"", "record an attributed session (Agent·Surface·Machine) + fold it in"),
        ("python3 wsx.py compact", "fold session fragments into the log (newest-first, idempotent)"),
    ]),
    ("Connect your other AI tools", [
        ("python3 wsx.py bridge list", "which AI tools you have + how each connects to this workspace"),
        ("python3 wsx.py bridge point", "make EVERY session (even outside this folder) auto-orient to the vault"),
        ("python3 wsx.py bridge extract", "copy other tools' memory into read-only quarantine (.wsx/quarantine/)"),
    ]),
    ("Grow the workspace", [
        ("python3 wsx.py skill add <name> --kind spoke|hub …", "create a skill skeleton, then enrich it"),
        ("python3 wsx.py project new \"<name>\"", "a per-project documentation folder"),
        ("python3 wsx.py project adopt <path>", "adopt an EXISTING repo/folder — reference-in-place"),
        ("python3 wsx.py ingest discover", "where your scattered notes/projects could come from (read-only)"),
        ("python3 wsx.py ingest <path> [--apply]", "pull outside content in — secret-scanned, consent-gated"),
        ("python3 wsx.py search \"<topic>\"", "find skill + reference sources for a new capability"),
        ("python3 wsx.py scan", "detect installed AI tools / MCP servers / local LLMs"),
    ]),
    ("Maintain & migrate", [
        ("python3 wsx.py diagnose", "report what's wrong/stale in this workspace (add --fix for the safe corrections)"),
        ("python3 wsx.py upgrade", "non-destructive corrective pass (adds missing pieces, reconnects the graph)"),
        ("python3 wsx.py restructure --apply", "migrate a legacy flat layout → numbered (dry-run by default; --rollback)"),
        ("python3 wsx.py examine", "read-only: what this workspace still needs"),
        ("python3 wsx.py archive <path> --reason \"…\"", "retire a note with provenance (never delete)"),
    ]),
    ("Hosting & identity (git)", [
        ("python3 wsx.py remote", "where the workspace lives online + free hosting options"),
        ("python3 wsx.py identity --name … --email …", "set the git author for THIS workspace only (never global)"),
        ("python3 wsx.py push", "finalize a fresh personal workspace: first commit + push"),
    ]),
]

_INTRO = ("**You rarely need these — your AI assistant drives them for you.** But if you (or an "
          "LLM) want to run one, this is the full set. Run them from the workspace root; the CLI "
          "is copied into `.wsx/`, so every command works here with **no install and no generator "
          "present**. On Windows use `wsx <cmd>` (the `wsx.cmd` shim) in place of `python3 wsx.py <cmd>`.")


def cheatsheet_md() -> str:
    """The COMMANDS.md content — the workspace's command reference."""
    out = ["# Command cheat sheet — `wsx`", "",
           "_Generated by `wsx`. The workspace's self-contained CLI (`.wsx/`) — safe to run "
           "anytime. Back to [[HOME]]._", "", _INTRO, ""]
    for section, rows in GROUPS:
        out.append(f"## {section}")
        out.append("")
        for cmd, blurb in rows:
            out.append(f"- `{cmd}`  \n  — {blurb}")
        out.append("")
    out += ["## First time here?",
            "",
            "Open this folder in your AI assistant (Claude Code, Cursor, …) and just talk to it —",
            "say *\"help me update my workspace\"* or *\"wrap up\"* and it runs the right commands. "
            "To make every future session anywhere auto-orient here, run `python3 wsx.py bridge point`.",
            ""]
    return "\n".join(out).rstrip() + "\n"


def help_text() -> str:
    """Compact terminal help for `wsx help`."""
    lines = ["wsx — command cheat sheet  (run from your workspace: python3 wsx.py <cmd>)", ""]
    for section, rows in GROUPS:
        lines.append(f"{section}:")
        for cmd, blurb in rows:
            short = cmd.replace("python3 wsx.py ", "wsx ")
            lines.append(f"  {short:44} {blurb}")
        lines.append("")
    lines.append("The CLI is copied into .wsx/ — every command runs here with no install.")
    lines.append("Full reference: COMMANDS.md in your workspace.  Also: wsx -h")
    return "\n".join(lines)


def write(root: Path) -> Path:
    """Write COMMANDS.md at the workspace root (create-or-refresh; it's generated)."""
    out = root / "COMMANDS.md"
    out.write_text(cheatsheet_md(), encoding="utf-8")
    return out
