"""The emitted MCP server, as a template.

`wsx emit mcp` writes SERVER_PY verbatim into the generated workspace at
adapters/mcp/server.py. It is deliberately **self-contained** — stdlib only, no
import of wsxlib — because the generated workspace is portable and must run without
the wsx generator being installed. The server discovers its own workspace root from
its file location, so no configuration is needed beyond pointing an MCP client at it.

Kept as a string (not a real .py in the tree) so it ships as workspace output, not
as part of the generator's own importable surface.
"""
from __future__ import annotations

# NOTE: outer delimiter is ''' so the server's own \"\"\" docstrings don't clash.
SERVER_PY = '''#!/usr/bin/env python3
"""workspace-mcp — a zero-dependency MCP server over a wsx workspace.

Generated by `wsx emit mcp`. Serves the canonical workspace (context/, skills/,
manifest.json) to any MCP client over stdio JSON-RPC 2.0 — Claude Desktop, Cursor,
Codex, or any local frontend. Stdlib only; does not import the wsx generator.

Workspace root is discovered from this file's location (…/adapters/mcp/server.py),
overridable with the WSX_WORKSPACE env var.
"""
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

WS = Path(os.environ.get("WSX_WORKSPACE") or Path(__file__).resolve().parents[2])
PROTOCOL_VERSION = "2024-11-05"
SERVER_INFO = {"name": "workspace-mcp", "version": "0.2"}

# The canonical boot context. Personal context is walled — loaded only on opt-in.
CORE_CONTEXT = [
    "context/profile.md",
    "context/project-context.md",
    "context/session-log.md",
]


def _read(p: Path) -> str:
    try:
        return p.read_text(encoding="utf-8")
    except OSError:
        return ""


def _manifest() -> dict:
    try:
        return json.loads((WS / "manifest.json").read_text(encoding="utf-8"))
    except Exception:
        return {}


def _frontmatter(text: str):
    if text.startswith("---"):
        end = text.find("\\n---", 3)
        if end != -1:
            return text[3:end].strip("\\n"), text[end + 4:].lstrip("\\n")
    return "", text


def _stamp() -> str:
    return datetime.now(timezone.utc).astimezone().strftime("%Y-%m-%d %H:%M %Z")


def tool_context_load(args: dict) -> str:
    sections = args.get("sections") or CORE_CONTEXT
    include_personal = bool(args.get("include_personal"))
    out = []
    for rel in sections:
        if "personal" in rel and not include_personal:
            continue  # privacy wall: personal context is opt-in only
        p = WS / rel
        if p.exists():
            out.append("===== " + rel + " =====\\n" + _read(p).strip())
    return "\\n\\n".join(out) if out else "(no context files found)"


def tool_skills_search(args: dict) -> str:
    q = (args.get("query") or "").lower().strip()
    skills = _manifest().get("skills", {})
    rows = []
    for name, rec in skills.items():
        hay = " ".join([name, rec.get("hub", "")] + list(rec.get("triggers", []))).lower()
        if not q or q in hay:
            rows.append((name, rec))
    if not rows:
        return "(no skills match " + repr(q) + ")"
    lines = []
    for name, rec in sorted(rows):
        trg = ", ".join(rec.get("triggers", []))
        lines.append("- " + name + "  [hub: " + rec.get("hub", "") + "] ("
                     + rec.get("source", "") + ")  triggers: " + trg)
    return str(len(rows)) + " skill(s):\\n" + "\\n".join(lines)


def tool_skills_load(args: dict) -> str:
    name = args.get("name", "")
    if not name:
        return "error: skills_load needs a 'name'"
    d = WS / "skills" / name
    sk = d / "SKILL.md"
    if not sk.exists():
        return "(no skill named " + repr(name) + " — try skills_search)"
    text = _read(sk)
    overlay = d / "overlay.md"
    if overlay.exists():  # compose pulled base + owned overlay, mirroring `wsx emit`
        _, ob = _frontmatter(_read(overlay))
        text = text.rstrip() + "\\n\\n---\\n\\n## House overlay (your deltas)\\n\\n" + ob.strip() + "\\n"
    return text


def tool_session_start(args: dict) -> str:
    return "session started " + _stamp() + " · workspace " + WS.name + "\\n\\n" + tool_context_load({})


def tool_session_end(args: dict) -> str:
    """Record the session as a conflict-free FRAGMENT — never by appending to the
    shared log. Two devices appending to one file is exactly the merge conflict the
    fragment model exists to prevent, and the log is newest-first so an append would
    also land in the wrong order. `wsx compact` folds fragments in (deduping on
    SessionID) at the next session start/end.
    """
    summary = (args.get("summary") or "").strip()
    now = datetime.now(timezone.utc).astimezone()
    sid = now.strftime("%Y-%m-%d-%H%M%S") + "-mcp"
    frag_dir = WS / "context" / "sessions"
    try:
        frag_dir.mkdir(parents=True, exist_ok=True)
        frag = frag_dir / (sid + ".md")
        frag.write_text(
            "### " + now.strftime("%Y-%m-%d") + " — session (via MCP)\\n\\n"
            "SessionID: " + sid + "\\n"
            "--- SESSION BLOCK ---\\n"
            "Date: " + now.strftime("%Y-%m-%d") + "\\n"
            "Stamp: " + _stamp() + "\\n"
            "Surface: MCP client\\n"
            "Summary: " + (summary or "(no summary provided)") + "\\n"
            "--- END BLOCK ---\\n",
            encoding="utf-8",
        )
        return ("session recorded as fragment context/sessions/" + sid + ".md "
                "(conflict-free). Run `wsx compact` to fold it into session-log.md.")
    except OSError as e:
        return "error writing session fragment: " + str(e)


def tool_reconcile(args: dict) -> str:
    return ("reconcile across machines is not yet in the MCP runtime — "
            "use `wsx session reconcile` (CLI) for now.")


TOOLS = [
    {"name": "context_load",
     "description": "Load the workspace's canonical context (profile, project-context, "
                    "session-log). Personal context is walled — excluded unless include_personal=true.",
     "inputSchema": {"type": "object", "properties": {
         "sections": {"type": "array", "items": {"type": "string"},
                      "description": "workspace-relative paths to load (default: core context)"},
         "include_personal": {"type": "boolean", "description": "opt in to personal context"}}}},
    {"name": "skills_search",
     "description": "Search the workspace skill network by name, hub, or trigger word.",
     "inputSchema": {"type": "object", "properties": {
         "query": {"type": "string", "description": "term to match (empty = list all)"}}}},
    {"name": "skills_load",
     "description": "Load a skill's full SKILL.md (pulled+patched skills are composed with their overlay).",
     "inputSchema": {"type": "object", "properties": {
         "name": {"type": "string", "description": "skill folder name"}}, "required": ["name"]}},
    {"name": "session_start",
     "description": "Begin a session: returns a boot summary plus the workspace context.",
     "inputSchema": {"type": "object", "properties": {}}},
    {"name": "session_end",
     "description": "End a session: append a session block (summary) to the session log.",
     "inputSchema": {"type": "object", "properties": {
         "summary": {"type": "string", "description": "what happened this session"}}}},
    {"name": "reconcile",
     "description": "Reconcile session blocks across machines (CLI-only for now).",
     "inputSchema": {"type": "object", "properties": {}}},
]

DISPATCH = {
    "context_load": tool_context_load,
    "skills_search": tool_skills_search,
    "skills_load": tool_skills_load,
    "session_start": tool_session_start,
    "session_end": tool_session_end,
    "reconcile": tool_reconcile,
}


def _ok(mid, result):
    return {"jsonrpc": "2.0", "id": mid, "result": result}


def _err(mid, code, message):
    return {"jsonrpc": "2.0", "id": mid, "error": {"code": code, "message": message}}


def handle(msg: dict):
    mid = msg.get("id")
    method = msg.get("method")
    params = msg.get("params") or {}
    if method == "initialize":
        return _ok(mid, {"protocolVersion": PROTOCOL_VERSION,
                         "capabilities": {"tools": {}},
                         "serverInfo": SERVER_INFO})
    if method in ("notifications/initialized", "notifications/cancelled"):
        return None  # notifications get no response
    if method == "ping":
        return _ok(mid, {})
    if method == "tools/list":
        return _ok(mid, {"tools": TOOLS})
    if method == "tools/call":
        name = params.get("name")
        fn = DISPATCH.get(name)
        if not fn:
            return _err(mid, -32601, "unknown tool: " + str(name))
        try:
            text = fn(params.get("arguments") or {})
            return _ok(mid, {"content": [{"type": "text", "text": text}]})
        except Exception as e:  # a tool error is a result with isError, not a protocol error
            return _ok(mid, {"content": [{"type": "text", "text": "error: " + str(e)}],
                             "isError": True})
    if mid is not None:
        return _err(mid, -32601, "unknown method: " + str(method))
    return None


def main():
    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue
        try:
            msg = json.loads(line)
        except json.JSONDecodeError:
            continue
        resp = handle(msg)
        if resp is not None:
            sys.stdout.write(json.dumps(resp) + "\\n")
            sys.stdout.flush()


if __name__ == "__main__":
    main()
'''
