"""Maps of Content (MOCs) — the connective tissue that makes the vault a graph.

Obsidian's graph view draws an edge for every LINK between notes. The generated
workspace was a scatter of islands because nothing linked to anything: skills sat
in `skills/<name>/SKILL.md`, frameworks referenced each other in bold text, and no
index tied the sections together.

This module regenerates the link layer from the current state of disk:
  * HOME.md              — the vault's front door; links every top-level section
  * skills/_INDEX.md     — hub→spoke tree, each skill a real relative link
  * projects/_INDEX.md   — one link per project (if any)

These files are GENERATED (safe to overwrite) — they carry a banner saying so.
Regenerate them from `init`, `skill add`, `skill reindex`, `emit`, `project new`,
and `upgrade`, so the graph stays connected as the workspace grows.

Why relative markdown links (not `[[wikilinks]]`): every skill file is named
`SKILL.md`, so a bare `[[SKILL]]` wikilink is ambiguous. A path-based markdown link
(`[name](skills/name/SKILL.md)`) both disambiguates AND renders as a graph edge.
"""
from __future__ import annotations

from pathlib import Path

from . import core, layout

_BANNER = ("_Generated by `wsx` (a Map of Content). Safe to skim, not to hand-edit —\n"
           "re-run `wsx emit` or `wsx upgrade` to regenerate the links from disk._")


# Link paths are stored as `sub` — RELATIVE TO the skills/ (or projects/) dir. The
# skills/projects index notes live in that dir, so they use `sub` verbatim; HOME.md
# lives at the vault root, so it prefixes `skills/` / `projects/`. Getting this right
# is what makes the links resolve (and the graph edges draw) in Obsidian AND on disk.
def _skill_rows(root: Path) -> list:
    rows = []
    for name, sk in core.iter_skills(root):
        fm, _ = core.parse_frontmatter(sk)
        rows.append({
            "name": name,
            "desc": str(fm.get("description", "")).strip(),
            "hub": str(fm.get("hub", "") or name),
            "kind": fm.get("kind", "spoke"),
            "source": fm.get("source", "generated"),
            "sub": f"{name}/SKILL.md",  # relative to skills/
        })
    return rows


def _projects(root: Path) -> list:
    """Each project is a folder under the projects dir with a PROJECT.md (docs, not code)."""
    pdir = layout.of(root).dir("projects")
    out = []
    if not pdir.is_dir():
        return out
    for d in sorted(pdir.iterdir()):
        if not d.is_dir() or d.name.startswith((".", "_")):
            continue
        doc = "PROJECT.md" if (d / "PROJECT.md").exists() else "README.md"
        out.append({"name": d.name, "sub": f"{d.name}/{doc}"})  # relative to projects/
    return out


# ------------------------------------------------------------------ skills MOC ---
def write_skills_index(root: Path) -> Path:
    rows = _skill_rows(root)
    lines = ["# Skills — Map of Content", "", _BANNER, "",
             "Reusable expertise the AI loads **only when relevant**, organized as",
             "**hubs** (broad areas) and **spokes** (focused skills). Back to [[HOME]].", ""]
    if not rows:
        lines += ["_(no skills yet — the interview + resolver populate these.)_", ""]
    else:
        by_hub: dict[str, list] = {}
        for r in rows:
            by_hub.setdefault(r["hub"], []).append(r)
        for hub in sorted(by_hub):
            members = by_hub[hub]
            hub_row = next((m for m in members if m["kind"] == "hub"), None)
            if hub_row:
                lines.append(f"## [{hub}]({hub_row['sub']}) — hub")
            else:
                lines.append(f"## {hub}")
            if hub_row and hub_row["desc"]:
                lines.append(f"_{hub_row['desc']}_")
            lines.append("")
            for m in sorted(members, key=lambda x: (x["kind"] != "hub", x["name"])):
                tag = " · hub" if m["kind"] == "hub" else ""
                if m["source"] != "generated":
                    tag += f" · {m['source']}"
                desc = f" — {m['desc']}" if m["desc"] else ""
                lines.append(f"- [{m['name']}]({m['sub']}){tag}{desc}")
            lines.append("")
    out = layout.of(root).dir("skills") / "_INDEX.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    return out


# ---------------------------------------------------------------- projects MOC ---
def write_projects_index(root: Path) -> Path:
    projects = _projects(root)
    lines = ["# Projects — Map of Content", "", _BANNER, "",
             "Per-project **documentation & context only** — specs, decisions, and",
             "handoff state. The code and assets live in each project's own repo, not",
             "here. Back to [[HOME]].", ""]
    if not projects:
        lines += ["_(no projects yet — create one: `wsx project new <name>`.)_", ""]
    else:
        for p in projects:
            lines.append(f"- [{p['name']}]({p['sub']})")
        lines.append("")
    out = layout.of(root).dir("projects") / "_INDEX.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    return out


# -------------------------------------------------------------------- HOME MOC ---
def write_home(root: Path) -> Path:
    prof = core.load_profile(root)
    name = str(prof.get("identity", {}).get("name", "you"))
    skills = _skill_rows(root)
    projects = _projects(root)
    walled = bool(prof.get("contexts", {}).get("personal", {}).get("private", True))
    lay = layout.of(root)
    C, S, F, P, K, SR, PR = (lay.name("context"), lay.name("skills"),
                             lay.name("frameworks"), lay.name("projects"),
                             lay.name("knowledge"), lay.name("shared"),
                             lay.name("preferences"))

    lines = [
        f"# {name}'s Workspace — HOME",
        "",
        _BANNER,
        "",
        "The front door to your second brain. Every section links out from here, so the",
        "Obsidian graph stays connected. Open the graph view to see it.",
        "",
        "## Context",
        f"- [**CRITICAL FACTS**]({C}/CRITICAL_FACTS.md) — read first; the tiny always-loaded hot cache.",
        f"- [Profile]({C}/profile.md) — who you are (machine source: `{C}/profile.yaml`).",
        f"- [Project context]({C}/project-context.md) — active projects + pending items.",
        f"- [Session log]({C}/session-log.md) — recent session history (newest first).",
        f"- [Open threads]({C}/open-threads.md) — non-project loose ends the close-out carries forward.",
        f"- [Memory]({C}/memory/MEMORY.md) — typed atomic facts/decisions/feedback the AI must never re-derive.",
        f"- [Decisions]({C}/decisions/README.md) — ADRs: why the meaningful choices were made.",
        f"- [Conventions]({C}/conventions.md) — typed edges · freshness · the note preamble.",
        f"- [Relational]({C}/relational.md) — the human texture of the working relationship.",
        f"- [Artifact registry]({C}/artifact-registry.md) — structural file index.",
    ]
    if not walled:
        lines.append(f"- [Personal]({C}/personal.md) — private notes (local-only when walled).")
    lines += [
        "",
        f"## [Frameworks]({F}/00-README.md)",
        f"- [Skill authoring (SUPREME)]({F}/skill-authoring.md) — how anything new gets built.",
        f"- [Working principles]({F}/principles.md) — how work is approached and judged.",
        "",
        f"## Shared references & preferences",
        f"- [Epistemic standards]({SR}/epistemic-standards.md) — the reasoning floor.",
        f"- [Working preferences]({PR}/user-preferences.md) — how the AI should work with you.",
        "",
        f"## [Skills]({S}/_INDEX.md) — {len(skills)} total",
    ]
    if skills:
        for r in sorted(skills, key=lambda x: (x["kind"] != "hub", x["name"]))[:12]:
            lines.append(f"- [{r['name']}]({S}/{r['sub']})")
        if len(skills) > 12:
            lines.append(f"- …and {len(skills) - 12} more → [skills index]({S}/_INDEX.md)")
    else:
        lines.append("- _(none yet — run the interview / `wsx skill add`.)_")
    lines += [
        "",
        f"## [Projects]({P}/_INDEX.md) — {len(projects)} total",
    ]
    if projects:
        for p in projects:
            lines.append(f"- [{p['name']}]({P}/{p['sub']})")
    else:
        lines.append("- _(none yet — `wsx project new <name>`.)_")
    lines += [
        "",
        f"## [Knowledge]({K}/README.md)",
        f"- [Index]({K}/_INDEX.md) — durable insight: validated patterns, constraints, research.",
        "",
        "## Running it yourself",
        "- [Command cheat sheet](COMMANDS.md) — every `wsx` command (run `python3 wsx.py <cmd>`).",
        "  You rarely need it — your AI drives the tools — but it's here if you or an LLM want to.",
        "",
        "## Adapters (generated — never hand-edit)",
        "AI-tool-specific files compiled from the canonical workspace. Re-run `wsx emit`.",
        "See `adapters/`, plus root `AGENTS.md` / `CLAUDE.md` and `.cursor/`.",
        "",
    ]
    out = root / "HOME.md"
    out.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    return out


# ----------------------------------------------------------- profile mirror ---
def write_profile_mirror(root: Path) -> Path:
    """Regenerate `context/profile.md` — the human-readable MIRROR of profile.yaml.

    This must be GENERATED, never rendered-once: it was previously stamped out at
    `wsx init` from the *default* profile and then never refreshed, so the moment the
    interview ran `wsx profile set surfaces.primary=…` the mirror disagreed with the
    machine source (profile.yaml said cursor, profile.md still said claude). Any file
    that restates profile.yaml has to be rebuilt whenever the profile changes.
    """
    prof = core.load_profile(root)

    def g(*path, default=""):
        cur = prof
        for p in path:
            if not isinstance(cur, dict) or p not in cur:
                return default
            cur = cur[p]
        if isinstance(cur, list):
            return ", ".join(str(x) for x in cur) or default
        return cur if cur not in (None, "") else default

    name = g("identity", "name", default="you")
    lines = [
        "# Profile (human-readable)",
        "",
        _BANNER,
        "",
        "> The machine-readable source of truth is **[profile.yaml](profile.yaml)** in this",
        "> folder. The AI reads that; this note is a friendly mirror for you — it is rebuilt",
        "> from the YAML on every `wsx profile set` / `emit` / `upgrade`, so it can't drift.",
        "",
        f"- **Name:** {name}",
        f"- **Primary AI assistant:** {g('surfaces', 'primary', default='(unset)')}",
        f"- **Emit targets:** {g('surfaces', 'agents', default='(unset)')}",
        f"- **Machines:** {g('surfaces', 'machines', default='(unset)')}",
        f"- **Model tier:** {g('models', 'tier', default='(unset)')}"
        f"{' · offline-capable' if prof.get('models', {}).get('offline') else ''}",
        f"- **Separation:** {g('lifecycle', 'separation', default='walled')} (work / personal kept apart)",
        f"- **Where it lives:** {g('transport', 'remote', default='(local only — see `wsx remote`)')}",
        "",
        "## Contexts",
        f"- **Work:** {g('contexts', 'work', 'role', default='(unspecified)')}",
        f"- **Professional crafts:** {g('contexts', 'professional', 'crafts', default='(unspecified)')}",
        f"- **Personal:** {'private (walled, local-only)' if prof.get('contexts', {}).get('personal', {}).get('private', True) else 'blended'}",
        "",
        "## Preferences",
        f"- **Tone:** {g('preferences', 'tone', default='(unspecified)')}",
        f"- **Audience:** {g('preferences', 'audience', default='(unspecified)')}",
        f"- **Verbosity:** {g('preferences', 'verbosity', default='(unspecified)')}",
        "",
        "Back to [[HOME]].",
    ]
    out = layout.of(root).dir("context") / "profile.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    return out


def write_mocs(root: Path) -> list:
    """Regenerate the whole connective layer. Returns the files written."""
    from . import commands, registry  # local import: no cycle via moc
    return [write_home(root), write_skills_index(root), write_projects_index(root),
            write_profile_mirror(root), registry.build(root), commands.write(root)]
