"""`wsx init` — scaffold a neutral, AI-agnostic workspace (vault + git + manifest).

v0 embeds the neutral templates here as strings (with {{placeholders}}) rather
than as files under templates/, so init has zero external-file dependencies and
is trivially reliable. Externalizing these to generator/templates/ is a planned
follow-up (see generator/templates/README.md).
"""
from __future__ import annotations

from pathlib import Path

from . import core


def default_profile(name: str = "you", handle: str = "you") -> dict:
    """A neutral, walled-by-default profile. The brain fills this in via `wsx profile set`."""
    return {
        "schema_version": "0.2",
        "identity": {"name": name, "handle": handle},
        "surfaces": {"primary": "claude", "agents": ["claude"], "machines": ["this-machine"]},
        "models": {"tier": "frontier", "offline": False},
        "transport": {"type": "git", "remote": ""},
        "contexts": {
            "work": {"role": "", "summary": ""},
            "professional": {"crafts": []},
            "personal": {"private": True, "interests": []},
        },
        "preferences": {"tone": "", "verbosity": "", "audience": "", "banned": []},
        "lifecycle": {"continuity": True, "separation": "walled", "automation": "standard"},
        "privacy": {"personal_local_only": True, "encrypt": False},
        "imports": [],
    }


# --- embedded neutral templates (relpath -> content with {{placeholders}}) ----
TEMPLATES: dict[str, str] = {
    "README.md": """# {{identity.name}}'s Workspace

_A personal second brain — an Obsidian vault that is also a git repo and is wired
into your AI assistant. Generated by the Bootstrap Generator (`wsx`)._

- **context/** — who you are, your projects, your session log (the AI reads these).
- **skills/** — reusable expertise the AI loads only when relevant (hubs + spokes).
- **frameworks/** — your operating principles.
- **adapters/** — generated, AI-tool-specific files (never hand-edit; re-run `wsx emit`).
- **manifest.json** — the routing index.

Open this folder in [Obsidian](https://obsidian.md) to browse it as a linked notebook.
""",
    ".gitignore": """# wsx workspace — git tracks the canonical workspace; ignore per-machine + private bits.

# Obsidian per-device UI state (not shared)
.obsidian/workspace*.json
.obsidian/cache
.obsidian/graph-*.json.bak

# Personal context is LOCAL-ONLY when walled (lifecycle.separation = walled)
context/personal.md

# AI tool runtime junk
.claude/sessions/
.claude/logs/
.claude/state/

# OS noise
.DS_Store
**/.DS_Store
Icon?
""",
    "context/profile.md": """# Profile (human-readable)

> The machine-readable source of truth is **profile.yaml** in this folder.
> The AI reads that; this note is a friendly mirror for you.

- **Name:** {{identity.name}}
- **Primary AI assistant:** {{surfaces.primary}}
- **Separation:** {{lifecycle.separation}} (work / personal kept apart)
""",
    "context/project-context.md": """# Project Context — {{identity.name}}

_Authoritative source for active projects and pending items._
_Last updated: {{date}}_

---

## Pending Items

### Active (next actions)
- [ ] _(none yet — your interview will seed these)_

### Deferred (resurface on context match)

---

## Active Projects

_(none yet)_
""",
    "context/session-log.md": """# Session Log — {{identity.name}}

_Newest first. The AI appends a Session Block here at the end of each session
(`wsx session end`)._

---

## Session Entries

_(none yet)_
""",
    "context/relational.md": """# Relational Context

_Optional. The human texture of the working relationship with your assistant —
not project state. Created the first time you ask to record a personal note._
""",
    "context/artifact-registry.md": """# Artifact Registry

_A per-file structural index the AI maintains so it doesn't re-read everything.
Populated as you work._
""",
    "context/personal.md": """# Personal Context (LOCAL-ONLY)

> ⚠️ This file is **gitignored by default** (walled separation). It stays on this
> machine and is never synced or shared unless you change `lifecycle.separation`
> to `blended` and remove the gitignore rule.

_Your dream projects, hobbies, finances, health, learning goals — whatever you
chose to share in the interview. Private by default._
""",
    "frameworks/00-README.md": """# Operating Frameworks

_Your top-level operating principles — the lens the AI applies above any single
skill. The generator seeds neutral starters here; make them yours._

- **principles.md** — how you want work approached and judged.

Add more as patterns emerge (critique, research standards, finishing discipline…).
""",
    "frameworks/principles.md": """# Working Principles

_Starter. Edit to fit {{identity.name}}._

- Lead with the answer; context after.
- Make uncertainty explicit; name tradeoffs and rejected alternatives.
- Verify before claiming done.
- Respect the privacy wall: personal context stays local unless opted in.
""",
    "skills/README.md": """# Skills

Reusable expertise the AI loads **only when relevant**. Organized as **hubs**
(broad areas) and **spokes** (sub-specialties). Each skill is a folder with a
`SKILL.md` (front matter: `name`, `description`, `triggers`, `domain`, `hub`,
`source`).

- **Pulled** skills (from a registry) are read-only; patches live in an overlay.
- **Generated** skills (your unique expertise) are authored here.

Run `wsx lint` to check for trigger overlaps. The interview + resolver populate
this folder; it starts empty.
""",
    ".obsidian/app.json": """{
  "alwaysUpdateLinks": true,
  "newLinkFormat": "shortest",
  "attachmentFolderPath": "04-attachments"
}
""",
    ".obsidian/appearance.json": """{
  "theme": "obsidian"
}
""",
    ".obsidian/core-plugins.json": """[
  "file-explorer",
  "global-search",
  "graph",
  "backlink",
  "outgoing-link",
  "tag-pane",
  "page-preview"
]
""",
}


def build_manifest(name: str) -> dict:
    return {
        "schema_version": "0.2",
        "generator": "wsx",
        "workspace": {"name": name, "created_with": f"wsx init ({core.today()})"},
        "skills": {},   # name -> {path, hub, triggers, source, hash}
        "emitted": {},  # target -> {files, at}
    }


def init(dest: str, name: str = "you", handle: str = "you",
         do_git: bool = True, force: bool = False) -> Path:
    root = Path(dest).resolve()
    if root.exists() and any(root.iterdir()) and not force:
        raise SystemExit(f"error: {root} is not empty (use --force to scaffold anyway)")
    root.mkdir(parents=True, exist_ok=True)

    prof = default_profile(name=name, handle=handle)
    ctx = dict(prof)
    ctx["date"] = core.today()

    written = []
    for rel, content in TEMPLATES.items():
        target = root / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(core.render(content, ctx), encoding="utf-8")
        written.append(rel)

    core.save_profile(root, prof)
    written.append("context/profile.yaml")
    core.save_manifest(root, build_manifest(name))
    written.append("manifest.json")

    if do_git:
        if not (root / ".git").exists():
            core.git(root, "init", "-q", check=False)
        core.git(root, "add", "-A", check=False)
        core.git(root, "commit", "-q", "-m", "wsx init: scaffold workspace", check=False)

    print(f"✓ wsx workspace scaffolded at {root}")
    print(f"  {len(written)} files · vault + git{' (committed)' if do_git else ''}")
    print("  next: run the interview (the brain) to fill in profile.yaml, then `wsx emit`.")
    return root
