// ─── Environment Management ────────────────────────────────────────────────────
// Default environments, variable helpers, env file generation, and validation.
// ──────────────────────────────────────────────────────────────────────────────

import type { Environment, EnvironmentVariable } from "./types";

/** Default environments that every project starts with */
export const DEFAULT_ENVIRONMENTS: Environment[] = [
  {
    id: "dev",
    name: "Development",
    type: "development",
    variables: {},
    isActive: true,
    color: "#22c55e", // green
  },
  {
    id: "staging",
    name: "Staging",
    type: "staging",
    variables: {},
    isActive: false,
    color: "#f59e0b", // amber
  },
  {
    id: "prod",
    name: "Production",
    type: "production",
    variables: {},
    isActive: false,
    color: "#ef4444", // red
  },
];

/** Create an environment variable */
export function createEnvVar(
  key: string,
  value: string,
  isSecret: boolean = false,
  description?: string,
): EnvironmentVariable {
  return { key, value, isSecret, description };
}

/** Generate .env file content for an environment */
export function generateEnvFile(env: Environment): string {
  const lines = [`# ${env.name} Environment`, `# Generated by Omni`, ""];
  for (const variable of Object.values(env.variables)) {
    if (variable.description) lines.push(`# ${variable.description}`);
    const value = variable.isSecret ? "***REDACTED***" : variable.value;
    lines.push(`${variable.key}=${value}`);
  }
  return lines.join("\n");
}

/** Validate environment variables (check for common issues) */
export function validateEnvironment(env: Environment): string[] {
  const warnings: string[] = [];
  for (const variable of Object.values(env.variables)) {
    if (!variable.key.match(/^[A-Z][A-Z0-9_]*$/)) {
      warnings.push(`Variable "${variable.key}" should use UPPER_SNAKE_CASE`);
    }
    if (variable.isSecret && variable.value.length < 8) {
      warnings.push(`Secret "${variable.key}" seems too short`);
    }
  }
  return warnings;
}
