#!/usr/bin/env python3
"""
build-trigger-routes.py

Generates 02-shared-references/trigger-routes.md from:
  1. curated routes in 02-shared-references/trigger-routes.json
  2. hub / foundation / cross-cutting skills with triggers in skills.registry.json

Usage:
    python3 09-tools/build-trigger-routes.py
    python3 09-tools/build-trigger-routes.py --check   # CI: fail on drift
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
WORKSPACE = SCRIPT_DIR.parent
CURATED = WORKSPACE / "02-shared-references" / "trigger-routes.json"
REGISTRY = WORKSPACE / "03-skills" / "skills.registry.json"
OUT = WORKSPACE / "02-shared-references" / "trigger-routes.md"


def expand(hint: str, templates: dict[str, str]) -> str:
    if hint.startswith("$") and hint[1:] in templates:
        return templates[hint[1:]]
    return hint


def build() -> str:
    curated = json.loads(CURATED.read_text(encoding="utf-8"))
    registry = json.loads(REGISTRY.read_text(encoding="utf-8"))
    templates = curated.get("templates", {})
    routes = curated.get("routes", {})
    skills = registry.get("skills", {})
    load_chains = registry.get("load_chains", {})

    lines: list[str] = [
        "# Trigger routes",
        "",
        "_Generated by `09-tools/build-trigger-routes.py`. Do not hand-edit._",
        "_Curated source: `02-shared-references/trigger-routes.json`. "
        "Skill graph: `03-skills/skills.registry.json`._",
        "",
        "## How to use (any agent)",
        "",
        "1. Match the user message against **Curated routes** first (insertion order = priority).",
        "2. Else match skill `triggers` / `description` in the registry; load "
        "`load_chains[name]` foundation → hub → spoke.",
        "3. Full algorithm: [AGENTS.md](../AGENTS.md) → Skills discovery / Skill loading precedence.",
        "",
        "Claude Code also injects curated matches via `.claude/hooks/dispatcher.py` "
        "(loads the same JSON). Cursor and other surfaces read this file + the registry directly.",
        "",
        "## Curated high-leverage routes",
        "",
        "| Trigger | Load hint |",
        "|---|---|",
    ]

    for trigger, hint in routes.items():
        expanded = expand(hint, templates).replace("|", "\\|").replace("\n", " ")
        # Keep table cells readable — truncate very long template expansions
        if len(expanded) > 180:
            expanded = expanded[:177] + "…"
        lines.append(f"| `{trigger}` | {expanded} |")

    lines += [
        "",
        "## Registry skills with triggers",
        "",
        "Hubs, foundations, and cross-cutting skills that declare `triggers:` in frontmatter.",
        "",
        "| Skill | Tier | Triggers (sample) | Load chain |",
        "|---|---|---|---|",
    ]

    rows: list[tuple[str, str, list[str], list[str]]] = []
    for name, meta in skills.items():
        tier = meta.get("tier") or ""
        if tier not in ("hub", "foundation", "cross-cutting"):
            continue
        triggers = meta.get("triggers") or []
        if not triggers:
            continue
        chain = load_chains.get(name) or [name]
        rows.append((name, tier, triggers, chain))

    tier_rank = {"foundation": 0, "hub": 1, "cross-cutting": 2}
    rows.sort(key=lambda r: (tier_rank.get(r[1], 9), r[0]))

    for name, tier, triggers, chain in rows:
        sample = ", ".join(f"`{t}`" for t in triggers[:6])
        if len(triggers) > 6:
            sample += f" (+{len(triggers) - 6})"
        chain_s = " → ".join(f"`{c}`" for c in chain)
        lines.append(f"| `{name}` | {tier} | {sample} | {chain_s} |")

    lines += [
        "",
        f"_Curated routes: {len(routes)} · Registry rows: {len(rows)}_",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if OUT would change")
    args = parser.parse_args()

    if not CURATED.exists():
        print(f"missing curated source: {CURATED}", file=sys.stderr)
        return 1
    if not REGISTRY.exists():
        print(f"missing registry: {REGISTRY}", file=sys.stderr)
        return 1

    body = build()
    if args.check:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != body:
            print("trigger-routes.md drift — run: python3 09-tools/build-trigger-routes.py")
            return 1
        print("trigger-routes.md OK")
        return 0

    OUT.write_text(body, encoding="utf-8")
    print(f"✓ wrote {OUT.relative_to(WORKSPACE)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
