#!/usr/bin/env python3
"""
compile-cursor-rules.py
Compiles Claude Workspace context files → AGENTS.md (universal agent fallback).

Usage:
    python3 09-tools/compile-cursor-rules.py          # one-shot
    python3 09-tools/compile-cursor-rules.py --watch  # file-watch mode

Run from Claude Workspace root or any subdirectory — script resolves the root
from its own location (09-tools/../).
"""

import re
import sys
import time
import argparse
from pathlib import Path

# ─── Paths ────────────────────────────────────────────────────────────────────

SCRIPT_DIR   = Path(__file__).resolve().parent
WORKSPACE    = SCRIPT_DIR.parent   # Claude Workspace root
AGENTS_OUT   = WORKSPACE / "AGENTS.md"

# Source files compiled into AGENTS.md (order = section order in output)
SOURCES = [
    ("Role & Context",      WORKSPACE / "06-context/role-and-context.md"),
    ("Preferences",         WORKSPACE / "03-preferences/user-preferences.md"),
    ("Active Projects",     WORKSPACE / "06-context/project-context.md"),
    ("Frameworks Summary",  WORKSPACE / "00-frameworks/00-README.md"),
]

# ─── Helpers ──────────────────────────────────────────────────────────────────

def strip_obsidian(text: str) -> str:
    """Remove Obsidian-specific syntax that confuses non-Obsidian consumers."""
    # Dataview blocks
    text = re.sub(r"```dataview.*?```", "", text, flags=re.DOTALL)
    # Wikilinks: [[target|alias]] → alias; [[target]] → target
    text = re.sub(r"\[\[([^\]|]+)\|([^\]]+)\]\]", r"\2", text)
    text = re.sub(r"\[\[([^\]]+)\]\]", r"\1", text)
    # YAML frontmatter
    text = re.sub(r"^---\n.*?\n---\n", "", text, flags=re.DOTALL)
    return text.strip()


def compile_agents_md() -> bool:
    """Build AGENTS.md from source files. Returns True if any source was missing."""
    header = (
        "# AGENTS.md — Universal Agent Context\n"
        "_Auto-generated by `09-tools/compile-cursor-rules.py`. Do not edit directly._\n"
        "_Source of truth: the Claude Workspace files listed below._\n"
        f"_Last compiled: {time.strftime('%Y-%m-%d %H:%M')} (local)_\n\n"
        "---\n\n"
        "## Agent Role Hierarchy\n\n"
        "Claude (claude-sonnet / claude-opus) is the filesystem controller for this workspace.\n"
        "All writes to `Claude Workspace/`, skills, context, and framework files must go through Claude.\n"
        "Non-Claude models should read this file for context and prompt the user to switch to Claude\n"
        "for any task that requires filesystem access or workspace mutation.\n\n"
        "See `.cursor/rules/01-agent-controller.mdc` for the full directive.\n\n"
        "---\n\n"
    )

    sections = []
    missing = False
    for title, src in SOURCES:
        if not src.exists():
            print(f"  ⚠  Missing source: {src.relative_to(WORKSPACE)}")
            missing = True
            continue
        content = strip_obsidian(src.read_text(encoding="utf-8"))
        sections.append(f"## {title}\n\n{content}")

    body = "\n\n---\n\n".join(sections)
    AGENTS_OUT.write_text(header + body + "\n", encoding="utf-8")
    print(f"  ✓  AGENTS.md ({len((header + body).splitlines())} lines)")
    return missing


def run_once():
    print("compile-cursor-rules.py — one-shot compile")
    missing = compile_agents_md()
    if missing:
        print("  ⚠  Some sources were missing — AGENTS.md may be incomplete.")
    else:
        print("  ✓  Done.")


def run_watch():
    """Poll source files for changes and recompile when any is modified."""
    try:
        from watchdog.observers import Observer
        from watchdog.events import FileSystemEventHandler

        class Handler(FileSystemEventHandler):
            def on_modified(self, event):
                if not event.is_directory and str(event.src_path).endswith(".md"):
                    changed = Path(event.src_path)
                    sources = [s for _, s in SOURCES]
                    if changed in sources:
                        print(f"\n→ Changed: {changed.name} — recompiling…")
                        compile_agents_md()

        observer = Observer()
        watch_dirs = {src.parent for _, src in SOURCES if src.exists()}
        for d in watch_dirs:
            observer.schedule(Handler(), str(d), recursive=False)
        observer.start()
        print(f"compile-cursor-rules.py — watching {len(watch_dirs)} director(ies)…")
        print("  Ctrl-C to stop.\n")
        compile_agents_md()   # initial compile
        try:
            while True:
                time.sleep(1)
        except KeyboardInterrupt:
            observer.stop()
        observer.join()

    except ImportError:
        print("watchdog not installed — falling back to polling (5s interval).")
        print("Install with: pip3 install watchdog\n")
        mtimes = {src: src.stat().st_mtime for _, src in SOURCES if src.exists()}
        compile_agents_md()
        while True:
            time.sleep(5)
            for _, src in SOURCES:
                if not src.exists():
                    continue
                mtime = src.stat().st_mtime
                if mtime != mtimes.get(src):
                    mtimes[src] = mtime
                    print(f"\n→ Changed: {src.name} — recompiling…")
                    compile_agents_md()


# ─── Entry point ──────────────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Compile Claude Workspace context → AGENTS.md")
    parser.add_argument("--watch", action="store_true", help="Watch source files and recompile on change")
    args = parser.parse_args()
    if args.watch:
        run_watch()
    else:
        run_once()
