#!/usr/bin/env python3
"""git_lanes.py — global config-based git lanes for every local committer (H18, wave 1).

The lanes are git >= 2.54 config-based hooks (`hook.<name>.command` / `.event` / `.enabled`) in one
rendered include that only Sean installs, through `workspace-doctor.sh --install-git-hooks` (the
installers.py `git-hooks` name: TTY + human verdict, diff + y/N, backup, byte-for-byte uninstall).
Every lane execs the PINNED copy of this file (`~/.config/snds-workspace/lib/current/09-tools/`), so
Cursor, Codex, Copilot, other local agents and humans all pass the same boundary. The Claude floor
(`ws-claude-wall`, from the Claude overlay) is a second channel and keeps its own semantics: for a
Claude chain the lane calls the same `profile_resolve.floor_decide`, so a lane is never weaker.

  git_lanes.py hook EVENT [HOOK_ARGS...]     stdin: pre-push ref lines (what the rendered command runs)
  git_lanes.py render [--check]              write/check 00-bootstrap/dist/git/lanes/ws-lanes.inc
  git_lanes.py audit [--repo DIR]... [--cache] [--home DIR] [--json]
  git_lanes.py --self-test

Lanes are stateless deciders: they read the repo and the pinned tables and write nothing, anywhere.
The lane is chosen by the repo profile (profile_resolve):
  employer   I1 over the commit identity (pre-commit, commit-msg, pre-merge-commit) and over every
             commit and annotated tag in a pushed range (author AND committer on the employer
             allowlist; any personal marker blocks). R2 (agent default-branch and force pushes) is
             report-only here, under H15's rollout. Nothing is ever written into an employer repo.
  workspace  identity as for personal, plus the H25 employer-substance scan over the staged files
             (blocks above its baseline) and the H1 heal lane (`nightly.py --lane pre-commit`).
  personal   the device-mismatch flag (a notice, never a block).
  unknown    agents WARN, humans are allowed.
A Claude chain (the most restrictive family anywhere in the chain; env markers only ever tighten)
first gets the Claude floor's own decision. An infrastructure error, a missing table or a timeout
allows with a notice (the wrapper exits 0): the Claude floor, the transport block and the servers
remain. Per-invocation bypasses (hook-skipping flags, per-command config, a redirected git config or
HOME) are declared residuals answered by H15's R6 rules and CI; config entries that replace, clear
or disable a lane at any scope are what `audit` (doctor --check) reports.

Exit codes: hook 0 allow · 1 block. render --check 1 on drift. audit 0 clean · 1 findings · 3 not
installed · 2 could not run. Stdlib only; Python 3.9+.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import os
import re
import subprocess
import sys
import tempfile
import threading
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

sys.dont_write_bytecode = True          # the pinned lib is read-only; never litter it

TOOLS = Path(__file__).resolve().parent
ROOT = TOOLS.parent
LANE_EVENTS = ("pre-commit", "commit-msg", "pre-merge-commit", "pre-push")
LANE_PREFIX = "ws-lane-"
LANES: Tuple[Tuple[str, str], ...] = tuple((LANE_PREFIX + ev, ev) for ev in LANE_EVENTS)
DIST_INCLUDE_REL = "00-bootstrap/dist/git/lanes/ws-lanes.inc"
INSTALL_INCLUDE_REL = ".config/snds-workspace/git/lanes/ws-lanes.inc"   # under HOME
PINNED_SELF_REL = ".config/snds-workspace/lib/current/09-tools/git_lanes.py"
GITCONFIG_BEGIN = "# BEGIN snds-workspace git lanes (installers.py git-hooks; do not edit)"
GITCONFIG_END = "# END snds-workspace git lanes"
LANE_BUDGET_S = 10.0
HEAL_TIMEOUT_S = 120.0
EMP_TIMEOUT_S = 30.0
GIT_TIMEOUT_S = 10
TAG = "ws-lanes"
AGENT_FAMILIES_R2 = ("cursor", "codex", "copilot", "gemini", "unknown-agent")

_PR = None      # test seam: a stand-in profile_resolve module


# --------------------------------------------------------------------------- rendering


def lane_command(event: str) -> str:
    """The shell command git runs for one lane. It carries no "$@": git appends the hook args.
    `python3 -I -S` keeps PYTHONPATH, site and user site hooks out of the pinned lib (and starts faster)."""
    return (f'L="$HOME/{PINNED_SELF_REL}"; command -v python3 >/dev/null 2>&1 || exit 0; '
            f'[ -f "$L" ] || exit 0; exec python3 -I -S "$L" hook {event}')


def _cfg_quote(value: str) -> str:
    """A git config value in double quotes (';' and '#' would start a comment unquoted)."""
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_include() -> str:
    lines = [
        "# snds-workspace git lanes (H18). Generated by 09-tools/git_lanes.py render; do not edit.",
        "# Installed only by a human: workspace-doctor.sh --install-git-hooks (included from ~/.gitconfig).",
        "# Global config-based hooks (git >= 2.54). Each lane execs the pinned git_lanes.py; with no",
        "# python3 or no pin the lane allows. Audit: python3 09-tools/git_lanes.py audit.",
    ]
    for name, event in LANES:
        lines += [f'[hook "{name}"]', f"\tcommand = {_cfg_quote(lane_command(event))}",
                  f"\tevent = {event}", "\tenabled = true"]
    return "\n".join(lines) + "\n"


def gitconfig_block(home: Path) -> str:
    """The managed ~/.gitconfig block the installer adds: one include line, nothing else."""
    return (f"{GITCONFIG_BEGIN}\n[include]\n\tpath = ~/{INSTALL_INCLUDE_REL}\n{GITCONFIG_END}\n")


def expected_lanes() -> Dict[str, dict]:
    return {name: {"command": lane_command(ev), "events": [ev], "enabled": True} for name, ev in LANES}


# --------------------------------------------------------------------------- profile_resolve


def _pr():
    global _PR
    if _PR is None:
        path = TOOLS / "profile_resolve.py"
        spec = importlib.util.spec_from_file_location("ws_lanes_profile_resolve", path)
        if spec is None or spec.loader is None:
            raise ImportError(str(path))
        mod = importlib.util.module_from_spec(spec)
        sys.modules["ws_lanes_profile_resolve"] = mod
        spec.loader.exec_module(mod)
        # One hook process asks for the LocalHostName several times (device, projects_root per resolve);
        # the answer cannot change within it, so the lane asks scutil once (same results, less latency).
        probe = getattr(mod, "_default_scutil", None)
        if callable(probe):
            box: dict = {}

            def _once():
                if "v" not in box:
                    box["v"] = probe()
                return box["v"]
            mod._default_scutil = _once
        _PR = mod
    return _PR


# --------------------------------------------------------------------------- decisions


def _allow(**kw) -> dict:
    d = {"decision": "allow", "rule": None, "reason": "", "notices": [], "lane": None, "family": None,
         "repo_class": None}
    d.update(kw)
    return d


def _block(base: dict, rule: str, reason: str, lane: str) -> dict:
    out = dict(base)
    out.update(decision="block", rule=rule, reason=reason, lane=lane)
    return out


def _employer_identity(dev_t: dict, pr) -> Optional[str]:
    ids = pr._identities(dev_t)
    for iid in (dev_t.get("employer_allowlist") or {}).get("identity_ids") or []:
        row = ids.get(iid)
        if row and row.get("email"):
            return f"{row.get('name') or ''} <{row['email']}>".strip()
    return None


def _commit_fix(dev_t: dict, pr) -> str:
    exp = _employer_identity(dev_t, pr)
    if not exp:
        return "set this repo's user.name and user.email to an identity on the employer allowlist, then retry"
    name, _, mail = exp.partition(" <")
    return (f"expected {exp}; run `git config user.name \"{name}\"` and `git config user.email "
            f"\"{mail.rstrip('>')}\"` in this repo, then retry")


def _push_fix(dev_t: dict, pr) -> str:
    exp = _employer_identity(dev_t, pr)
    who = f"the employer identity {exp}" if exp else "an identity on the employer allowlist"
    return (f"rewrite those commits with {who} (set user.name and user.email in this repo, then "
            "`git rebase --exec 'git commit --amend --no-edit --reset-author' <upstream>`), then push again")


def _locate(pr, here: Path, e: dict, git: str) -> tuple:
    """(git dir, work tree, remote urls as git resolves the repo config): the floor's own readers."""
    gitdir, top = pr._floor_locate(here, e, git)
    cfg = pr._floor_config_remotes(here, gitdir, e, git) if (gitdir is not None or top is not None) else None
    return gitdir, top, cfg


def _classify(pr, here: Path, e: dict, det: dict, hook_args: List[str], event: str, root, home, git: str,
              loc: Optional[tuple] = None) -> dict:
    """Repo facts, most restrictive of every source (the floor's own reading, plus path globs)."""
    url_cls = "none"
    if event == "pre-push" and len(hook_args) >= 2:
        cls2 = [pr._push_url_class(str(a), root) for a in hook_args[:2]]
        url_cls = max(cls2, key=lambda c: pr.CLASS_RANK.get(c, -1))
    gitdir, top, cfg_urls = loc if loc is not None else _locate(pr, here, e, git)
    facts = {"gitdir": gitdir, "top": top, "url_cls": url_cls, "res": {}, "employer": url_cls == "employer",
             "role": "unknown", "owner_class": "unknown", "positively_personal": False, "profile": None,
             "cfg_urls": None}
    if gitdir is None and top is None:
        return facts
    res: dict = {}
    if top is not None:
        res = pr.repo_resolve(str(top), root=root, home=home, detection=det)
        main = pr._main_checkout(top)
        if main is not None:
            mres = pr.repo_resolve(str(main), root=root, home=home, detection=det)
            res = dict(res, owner_class=max((res.get("owner_class"), mres.get("owner_class")),
                                            key=lambda c: pr.CLASS_RANK.get(str(c), pr.CLASS_RANK["unknown"])),
                       positively_personal=bool(res.get("positively_personal") and mres.get("positively_personal")),
                       role=res.get("role") if res.get("role") == "workspace" else mres.get("role"))
    cfg_cls = [pr._push_url_class(u, root) for u in cfg_urls or []]
    glob = None
    if top is not None:
        table = pr._try_table("context-remotes", root) or {}
        glob = pr._glob_hit(pr._real(top), pr.projects_root(root=root, home=home),
                            list(table.get("employer_path_globs") or []))
    employer = (res.get("owner_class") == "employer" or url_cls == "employer" or "employer" in cfg_cls
                or bool(glob))
    facts.update(res=res, employer=employer, role=str(res.get("role") or "unknown"),
                 owner_class="employer" if employer else str(res.get("owner_class") or "unknown"),
                 positively_personal=bool(res.get("positively_personal")) and not employer,
                 profile=res.get("profile"), cfg_urls=cfg_urls)
    return facts


def _r2_notices(pr, facts: dict, event: str, stdin_lines: List[str], walls: str, e: dict, git: str) -> List[str]:
    """R2 for non-Claude agents on employer repos, REPORT-ONLY in wave 1 (H15 rollout): notices only."""
    if walls not in AGENT_FAMILIES_R2:
        return []
    top = facts.get("top")
    cur, dflt = pr._repo_heads(top) if top is not None else (None, None)
    prof = facts.get("profile") or "centric-engineering"
    out = []
    if event in ("pre-commit", "pre-merge-commit") and cur and pr._ref_kind(cur, dflt) == "default":
        out.append(f"R2 report-only: would deny an agent commit on the default branch {cur!r} (profile {prof})")
    if event == "pre-push":
        genv = pr._clean_git_env(e)
        for ln in pr._push_lines(stdin_lines):
            if ln.get("bad") or not ln["remote_ref"].startswith("refs/heads/"):
                continue
            ref = ln["remote_ref"]
            if pr._ref_kind(ref, dflt) == "default":
                what = "a deletion of" if pr._ZERO_SHA_RE.match(ln["local_sha"]) else "a push to"
                out.append(f"R2 report-only: would deny {what} the default branch {pr._short_ref(ref)!r} "
                           f"(profile {prof})")
            elif not pr._ZERO_SHA_RE.match(ln["remote_sha"]) and not pr._ZERO_SHA_RE.match(ln["local_sha"]):
                r = pr._git_run(["merge-base", "--is-ancestor", ln["remote_sha"], ln["local_sha"]],
                                top if top is not None else Path("."), genv, git)
                if r is not None and r.returncode == 1:
                    out.append(f"R2 report-only: would deny a force-push to {pr._short_ref(ref)!r} (profile {prof})")
    return out


def _employer_lane(pr, base: dict, facts: dict, event: str, hook_args: List[str], stdin_lines: List[str],
                   here: Path, e: dict, root, git: str) -> dict:
    dev_t = pr._try_table("devices", root)
    if dev_t is None:
        base["notices"].append("devices table unavailable: employer identity check skipped (fail-open)")
        return base
    if event != "pre-push":
        idents = pr._commit_idents(here, e, git)
        if not idents:
            base["notices"].append("commit identity unreadable; git itself refuses a commit with no identity")
        for role, em in idents:
            cls = pr.email_class(em, dev_t)
            if cls != "employer":
                what = "a personal identity" if cls == "personal" else "an identity not on the employer allowlist"
                return _block(base, "I1", f"{event}: the {role} identity {em!r} is {what}; an employer repo takes "
                                          f"only employer identities; {_commit_fix(dev_t, pr)}", "employer")
        return base
    remote = str(hook_args[0]) if hook_args else "origin"
    genv = pr._clean_git_env(e)
    top, gitdir = facts.get("top"), facts.get("gitdir")
    for ln in pr._push_lines(stdin_lines):
        if ln.get("bad"):
            continue
        try:
            idents, tags_ok = pr._push_idents(top if top is not None else here, ln, remote, genv, git, gitdir)
        except pr._TagChainTooDeep as exc:
            return _block(base, "I1", f"annotated tag chain from {str(exc)[:12]} is too long to check its "
                                      "taggers (I1)", "employer")
        if not tags_ok:
            base["notices"].append("I1 tag check unavailable (git error)")
        if idents is None:
            base["notices"].append("I1 range check unavailable (git error); CI re-checks the pushed range")
            continue
        for kind, sha, role, em in idents:
            cls = pr.email_class(em, dev_t)
            if cls != "employer":
                what = "a personal identity" if cls == "personal" else "an identity not on the employer allowlist"
                return _block(base, "I1", f"{kind} {sha[:12]} in the push has {what} as {role}; an employer repo "
                                          f"takes only employer identities, whatever created the commit; "
                                          f"{_push_fix(dev_t, pr)}", "employer")
    return base


def _heal_lane(base: dict, top: Path, e: dict) -> dict:
    """H1: the workspace's own stateless pre-commit lane (nightly.py --lane pre-commit), run from
    the checkout being committed. Missing or broken: allow with a notice (CI re-checks)."""
    script = top / "09-tools" / "nightly.py"
    if not script.is_file():
        return base
    try:
        r = subprocess.run([sys.executable, str(script), "--lane", "pre-commit"], cwd=str(top), env=e,
                           capture_output=True, text=True, timeout=HEAL_TIMEOUT_S)
    except (OSError, subprocess.SubprocessError) as exc:
        base["notices"].append(f"H1 heal lane could not run ({exc.__class__.__name__}); CI re-checks")
        return base
    if r.returncode == 1:
        return _block(base, "H1", (r.stderr or "").strip() or "generated files are stale", "workspace")
    if r.stderr.strip():
        base["notices"].append(r.stderr.strip().splitlines()[-1])
    return base


def _emp_lane(base: dict, top: Path, e: dict) -> dict:
    """H25 (W1-10): the employer-substance scan over the staged files, blocking against the baseline
    (`check-secrets.py --class employer-substance --baseline-check --staged`, from the checkout being
    committed). Exit 1 blocks; a missing script, a timeout or any other exit allows with a notice
    (CI runs the full-tree check on every push)."""
    script = top / "09-tools" / "check-secrets.py"
    if not script.is_file():
        return base
    try:
        r = subprocess.run([sys.executable, str(script), "--class", "employer-substance", "--baseline-check",
                            "--staged"], cwd=str(top), env=e, capture_output=True, text=True,
                           timeout=EMP_TIMEOUT_S)
    except (OSError, subprocess.SubprocessError) as exc:
        base["notices"].append(f"H25 employer-substance scan could not run ({exc.__class__.__name__}); CI re-checks")
        return base
    if r.returncode == 1:
        # The scan prints `path rule count > baseline` lines only; matched text is never printed.
        lines = [ln.strip() for ln in (r.stderr or "").splitlines() if ln.strip()]
        return _block(base, "H25", "; ".join(lines[-6:]) or "employer-substance baseline exceeded", "workspace")
    if r.returncode != 0:
        base["notices"].append(f"H25 employer-substance scan exited {r.returncode}; CI re-checks")
    return base


def lane_decide(event: str, hook_args: Optional[list] = None, stdin_lines: Optional[list] = None, *,
                env: Optional[dict] = None, ancestry: Optional[list] = None, root: Optional[Path] = None,
                home: Optional[Path] = None, cwd: Optional[Any] = None, hostname: Optional[str] = None,
                git: str = "git", heal: bool = True) -> dict:
    """{decision: allow|block, rule, reason, notices[], lane, family, repo_class}. Stateless."""
    pr = _pr()
    args = [str(a) for a in hook_args or []]
    lines = [str(x) for x in stdin_lines or []]
    if event not in LANE_EVENTS:
        return _allow(notices=[f"unknown lane event {event!r}; allowing"])
    e = dict(os.environ if env is None else env)
    here = pr._real(cwd if cwd is not None else os.getcwd())
    # Detection (a process-table walk) and the repo readers (git spawns) are independent: run them
    # side by side to stay near the hook budget. A reader error surfaces here as it would inline.
    loc_box: dict = {}

    def _loc():
        try:
            loc_box["v"] = _locate(pr, here, e, git)
        except BaseException as exc:  # noqa: BLE001
            loc_box["e"] = exc

    th = threading.Thread(target=_loc, daemon=True)
    th.start()
    det = pr.detect_surface(env=e, ancestry=ancestry, root=root)
    th.join()
    if "e" in loc_box:
        raise loc_box["e"]
    walls = str(det.get("family_for_walls") or "unknown")
    base = _allow(family=walls)
    # 1. A Claude chain gets the Claude floor's own decision first: the lane is never weaker than it.
    if walls == "claude":
        v = pr.floor_decide(event, args, lines, env=e, ancestry=ancestry, root=root, home=home, cwd=here, git=git)
        if v.get("decision") == "block":
            return _block(base, str(v.get("rule") or "I2"), str(v.get("reason") or ""), "claude-floor")
        if v.get("notice"):
            base["notices"].append(f"claude floor: {v['notice']}")
    # 2. The repo profile picks the lane.
    facts = _classify(pr, here, e, det, args, event, root, home, git, loc_box.get("v"))
    if facts["gitdir"] is None and facts["top"] is None:
        base["notices"].append("not inside a repository; allowing")
        return base
    base["repo_class"] = facts["owner_class"]
    if facts["employer"]:
        base["lane"] = "employer"
        out = _employer_lane(pr, base, facts, event, args, lines, here, e, root, git)
        if out["decision"] == "block":
            return out
        out["notices"] += _r2_notices(pr, facts, event, lines, walls, e, git)
        return out
    top = facts["top"]
    if facts["role"] == "workspace":
        base["lane"] = "workspace"
    elif facts["positively_personal"]:
        base["lane"] = "personal"
    else:
        base["lane"] = "unknown"
        fams = (pr._surfaces_or_fallback(root).get("families") or {})
        if walls != "claude" and (fams.get(walls) or {}).get("agent") and event in ("pre-commit", "pre-push"):
            base["notices"].append(f"WARN: this repo's owner is not declared personal ({facts['owner_class']}); "
                                   "an agent works here only with Sean's say-so (run profile_resolve.py scan in "
                                   "a plain terminal, or declare the owner in context-remotes.json)")
    if event == "pre-commit" and top is not None:
        try:
            idn = pr.identity(repo=str(top), root=root, env=e, ancestry=ancestry, home=home, hostname=hostname,
                              detection=det, git=git)
            if idn.get("flag"):
                base["notices"].append(f"flag: {idn['flag']}")
        except Exception as exc:  # noqa: BLE001 - a flag is advisory; never block on its failure
            base["notices"].append(f"identity flag unavailable ({exc.__class__.__name__})")
        if base["lane"] == "workspace" and heal:
            base = _emp_lane(base, top, e)
            if base.get("decision") == "block":
                return base
            return _heal_lane(base, top, e)
    return base


def run_hook(event: str, hook_args: List[str], stdin_lines: List[str], *, budget: float = LANE_BUDGET_S,
             err=None, decide=None) -> int:
    """The hook path: 1 on a block, 0 otherwise (an exception or a timeout allows with a notice)."""
    err = err or sys.stderr
    fn = decide or lane_decide
    box: dict = {}

    def work():
        try:
            box["v"] = fn(event, hook_args, stdin_lines)
        except BaseException as exc:  # noqa: BLE001
            box["e"] = exc

    th = threading.Thread(target=work, daemon=True)
    th.start()
    th.join(budget)
    if th.is_alive():
        print(f"{TAG}: lane timed out after {budget:g}s; allowing", file=err)
        return 0
    if "e" in box:
        print(f"{TAG}: lane error ({type(box['e']).__name__}); allowing", file=err)
        return 0
    v = box.get("v") if isinstance(box.get("v"), dict) else {}
    for n in v.get("notices") or []:
        print(f"{TAG}: {n}", file=err)
    if v.get("decision") == "block":
        print(f"{TAG}: blocked [{v.get('rule') or 'unknown'}] {v.get('reason') or ''}".rstrip(), file=err)
        return 1
    return 0


# --------------------------------------------------------------------------- audit (doctor --check)


def _clean_env(env: Optional[dict] = None) -> dict:
    e = dict(os.environ if env is None else env)
    for k in list(e):
        if k.startswith("GIT_CONFIG_") or k in ("GIT_CONFIG_PARAMETERS", "GIT_CONFIG", "GIT_DIR", "GIT_WORK_TREE",
                                                  "GIT_INDEX_FILE", "GIT_COMMON_DIR", "GIT_CEILING_DIRECTORIES"):
            e.pop(k, None)
    e["GIT_TERMINAL_PROMPT"] = "0"
    return e


def parse_listing(raw: bytes) -> List[dict]:
    """`git config --show-scope --show-origin -z --get-regexp` output → [{scope, origin, key, value}]."""
    parts = raw.decode("utf-8", "replace").split("\0")
    out = []
    i = 0
    while i + 2 < len(parts):
        scope, origin, kv = parts[i], parts[i + 1], parts[i + 2]
        i += 3
        key, nl, value = kv.partition("\n")
        out.append({"scope": scope, "origin": origin, "key": key, "value": value if nl else None})
    return out


def _bool(v: Optional[str]) -> bool:
    return v is None or str(v).strip().lower() in ("true", "yes", "on", "1")


def effective(entries: List[dict]) -> Dict[str, dict]:
    """Per lane name, what git will use: last command, last enabled, the event list with empty resets;
    `last` records where each of those was last set."""
    out: Dict[str, dict] = {}
    for ent in entries:
        m = re.fullmatch(r"hook\.(.+)\.(command|event|enabled)", ent["key"], flags=re.I)
        if not m:
            continue
        name, field = m.group(1), m.group(2).lower()
        cur = out.setdefault(name, {"command": None, "events": [], "enabled": True, "last": {}, "entries": []})
        cur["entries"].append(ent)
        if field == "command":
            cur["command"] = ent["value"]
        elif field == "enabled":
            cur["enabled"] = _bool(ent["value"])
        elif not (ent["value"] or "").strip():
            cur["events"] = []
        else:
            cur["events"].append(ent["value"].strip())
        cur["last"][field] = f"{ent['scope']} {ent['origin']}"
    return out


def _origin_path(origin: str, cwd: Optional[Path]) -> Optional[Path]:
    if not origin.startswith("file:"):
        return None
    p = Path(origin[len("file:"):])
    if not p.is_absolute() and cwd is not None:
        p = cwd / p
    return p


def _inside_repo(path: Path) -> Optional[Path]:
    cur = path.parent
    for _ in range(64):
        try:
            if (cur / ".git").exists():
                return cur
        except OSError:
            return None
        if cur.parent == cur:
            return None
        cur = cur.parent
    return None


def _cf(p: Any) -> str:
    return os.path.realpath(str(p)).casefold()


def findings_for(entries: List[dict], *, home: Path, where: str, cwd: Optional[Path] = None) -> List[str]:
    """Every way the effective lane config differs from the rendered lanes, with where it was set."""
    want = expected_lanes()
    inc = home / INSTALL_INCLUDE_REL
    eff = effective([x for x in entries if x["key"].lower().startswith("hook." + LANE_PREFIX)])
    out: List[str] = []
    for name, exp in want.items():
        got = eff.get(name)
        if got is None or got["command"] is None:
            out.append(f"{where}: lane {name} missing (no command in any scope)")
            continue
        if got["command"] != exp["command"]:
            out.append(f"{where}: lane {name} command replaced (last set at {got['last'].get('command')})")
        if exp["events"][0] not in got["events"]:
            out.append(f"{where}: lane {name} event cleared or missing (last event entry at "
                       f"{got['last'].get('event', 'nowhere')})")
        extra = [ev for ev in got["events"] if ev not in exp["events"]]
        if extra:
            out.append(f"{where}: lane {name} runs on extra events {extra} (last at {got['last'].get('event')})")
        if not got["enabled"]:
            out.append(f"{where}: lane {name} disabled (enabled=false at {got['last'].get('enabled')})")
        for ent in got["entries"]:
            p = _origin_path(ent["origin"], cwd)
            if p is None or _cf(p) != _cf(inc):
                out.append(f"{where}: {ent['key']} set outside the lane include ({ent['scope']} {ent['origin']})")
            elif _inside_repo(p) is not None:
                out.append(f"{where}: the lane include {p} lies inside a git repository")
    for name in sorted(set(eff) - set(want)):
        out.append(f"{where}: unexpected hook {name} uses the reserved {LANE_PREFIX} prefix "
                   f"({eff[name]['last'].get('command') or eff[name]['last']})")
    return list(dict.fromkeys(out))


def _listing(cwd: Path, env: dict, git: str) -> Optional[List[dict]]:
    try:
        r = subprocess.run([git, "config", "--show-scope", "--show-origin", "-z", "--get-regexp", r"^hook\."],
                           cwd=str(cwd), env=env, capture_output=True, timeout=GIT_TIMEOUT_S)
    except (OSError, subprocess.SubprocessError):
        return None
    if r.returncode not in (0, 1):
        return None
    return parse_listing(r.stdout)


def _hook_list(cwd: Path, env: dict, git: str, event: str) -> Optional[str]:
    try:
        r = subprocess.run([git, "hook", "list", "--show-scope", event], cwd=str(cwd), env=env,
                           capture_output=True, text=True, timeout=GIT_TIMEOUT_S)
    except (OSError, subprocess.SubprocessError):
        return None
    return r.stdout if r.returncode in (0, 1) else None


def _cache_repos(home: Path) -> List[dict]:
    try:
        obj = json.loads((home / ".config" / "snds-workspace" / "telemetry" / "checkouts.json").read_text("utf-8"))
    except (OSError, ValueError):
        return []
    return [c for c in obj.get("checkouts") or [] if isinstance(c, dict) and isinstance(c.get("path"), str)]


def audit(*, repos: Optional[List[str]] = None, use_cache: bool = False, home: Optional[Path] = None,
          env: Optional[dict] = None, git: str = "git", ancestry: Optional[list] = None,
          dist: Optional[Path] = None) -> dict:
    """The doctor --check audit: {status: clean|findings|absent|error, installed, findings[], notices[],
    repos_checked, repos_skipped}. Reads config only; never writes."""
    home = Path(home) if home is not None else Path.home()
    e = _clean_env(env)
    e["HOME"] = str(home)
    notices: List[str] = []
    findings: List[str] = []
    src = dict(os.environ if env is None else env)
    for k in ("GIT_CONFIG_GLOBAL", "GIT_CONFIG_NOSYSTEM"):
        if src.get(k):
            notices.append(f"{k} is set in this environment: a git run with it would not read the global lanes")
    inc = home / INSTALL_INCLUDE_REL
    dist = dist or (ROOT / DIST_INCLUDE_REL)
    installed = inc.is_file()
    if installed:
        try:
            if dist.is_file() and inc.read_bytes() != dist.read_bytes():
                findings.append(f"{inc} differs from {DIST_INCLUDE_REL} — review, then run workspace-doctor.sh "
                                "--install-git-hooks")
        except OSError:
            findings.append(f"{inc} unreadable")
        if _inside_repo(inc) is not None:
            findings.append(f"{inc} lies inside a git repository (the lanes must not live in a repo)")
    with tempfile.TemporaryDirectory(prefix="ws-lanes-audit-") as td:
        neutral = Path(td)
        ents = _listing(neutral, e, git)
        if ents is None:
            return {"status": "error", "installed": installed, "findings": findings,
                    "notices": notices + ["git config unreadable"], "repos_checked": 0, "repos_skipped": 0}
        lane_ents = [x for x in ents if x["key"].lower().startswith("hook." + LANE_PREFIX)]
        if not installed and not lane_ents:
            return {"status": "absent", "installed": False, "findings": findings, "notices": notices,
                    "repos_checked": 0, "repos_skipped": 0}
        findings += findings_for(ents, home=home, where="global")
        for name, ev in LANES:
            out = _hook_list(neutral, e, git, ev)
            if out is None:
                notices.append(f"git hook list {ev} unavailable (git < 2.54?)")
            elif not any(ln.split("\t")[-1] == name and "disabled" not in ln.split("\t") for ln in out.splitlines()):
                findings.append(f"global: git hook list {ev} does not show {name} enabled")
    targets: List[Tuple[str, Optional[str]]] = [(r, None) for r in repos or []]
    if use_cache:
        targets += [(c["path"], c.get("owner_class")) for c in _cache_repos(home)]
    checked = skipped = 0
    claude = False
    try:
        det = _pr().detect_surface(env=src, ancestry=ancestry)
        claude = det.get("family_for_walls") == "claude" or bool(det.get("agent_possible"))
    except Exception:  # noqa: BLE001 - undetermined: treat as Claude (never open a non-personal repo)
        claude = True
    seen = set()
    for path, oc in targets:
        p = Path(path)
        if _cf(p) in seen or not p.exists():
            continue
        seen.add(_cf(p))
        if claude:
            try:
                personal = oc == "personal" if oc is not None else bool(
                    _pr().repo_resolve(str(p), home=home, detection=det).get("positively_personal"))
            except Exception:  # noqa: BLE001
                personal = False
            if not personal:
                skipped += 1
                continue
        ents = _listing(p, e, git)
        if ents is None:
            notices.append(f"{p}: git config unreadable")
            continue
        checked += 1
        findings += findings_for(ents, home=home, where=str(p), cwd=p)
    if skipped:
        notices.append(f"{skipped} non-personal repo(s) not audited from an agent chain (run the doctor in a "
                       "plain terminal)")
    findings = list(dict.fromkeys(findings))
    return {"status": "findings" if findings else "clean", "installed": installed, "findings": findings,
            "notices": notices, "repos_checked": checked, "repos_skipped": skipped}


# --------------------------------------------------------------------------- CLI


def _read_lines() -> List[str]:
    try:
        if sys.stdin is None or sys.stdin.isatty():
            return []
        return [ln.rstrip("\n") for ln in sys.stdin.read().splitlines() if ln.strip()]
    except (OSError, ValueError):
        return []


def cmd_render(check: bool) -> int:
    path = ROOT / DIST_INCLUDE_REL
    want = render_include()
    have = path.read_text(encoding="utf-8") if path.is_file() else None
    if check:
        if have != want:
            print(f"git_lanes: {DIST_INCLUDE_REL} is stale; run python3 09-tools/git_lanes.py render", file=sys.stderr)
            return 1
        return 0
    if have != want:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(want, encoding="utf-8")
        print(f"wrote {DIST_INCLUDE_REL}")
    return 0


def main(argv: Optional[List[str]] = None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)
    if argv[:1] == ["--self-test"]:
        return self_test()
    if argv[:1] == ["hook"]:
        # Hook path: never a usage error that blocks. git appends the hook's own args after the event.
        if len(argv) < 2:
            return 0
        event, hook_args = argv[1], argv[2:]
        # pre-commit may run the workspace's H25 scan and H1 lane (their own timeouts); every other event
        # gets the lane budget.
        budget = LANE_BUDGET_S + (EMP_TIMEOUT_S + HEAL_TIMEOUT_S if event == "pre-commit" else 0)
        try:
            return run_hook(event, hook_args, _read_lines() if event == "pre-push" else [], budget=budget)
        except BaseException as exc:  # noqa: BLE001
            if isinstance(exc, KeyboardInterrupt):
                raise
            print(f"{TAG}: {exc.__class__.__name__} in the lane; allowing", file=sys.stderr)
            return 0
    ap = argparse.ArgumentParser(prog="git_lanes.py")
    sub = ap.add_subparsers(dest="cmd")
    r = sub.add_parser("render")
    r.add_argument("--check", action="store_true")
    a = sub.add_parser("audit")
    a.add_argument("--repo", action="append", default=[])
    a.add_argument("--cache", action="store_true")
    a.add_argument("--home")
    a.add_argument("--json", action="store_true")
    ns = ap.parse_args(argv)
    if ns.cmd == "render":
        return cmd_render(ns.check)
    if ns.cmd == "audit":
        res = audit(repos=ns.repo, use_cache=ns.cache, home=Path(ns.home) if ns.home else None)
        if ns.json:
            print(json.dumps(res, indent=2))
        else:
            for f in res["findings"]:
                print(f"FINDING: {f}")
            for n in res["notices"]:
                print(f"NOTE: {n}")
            print(f"git lanes: {res['status']} (repos checked {res['repos_checked']}, skipped {res['repos_skipped']})")
        return {"clean": 0, "findings": 1, "absent": 3}.get(res["status"], 2)
    ap.print_help(sys.stderr)
    return 2


# --------------------------------------------------------------------------- self-test


def self_test() -> int:
    """Unit cases here; the temp-HOME git fixtures live in fixtures/git_lanes/lane_cases.py
    (0 pass · 1 fail · 3 a case SKIPPED, never green)."""
    fails: List[str] = []
    skips: List[str] = []
    n = [0]

    def ok(cond: Any, label: str) -> None:
        n[0] += 1
        if not cond:
            fails.append(label)
            print(f"FAIL {label}", file=sys.stderr)

    inc = render_include()
    ok(inc.count("[hook \"ws-lane-") == len(LANE_EVENTS), "render: one hook section per lane event")
    ok("\"$@\"" not in inc, "render: no \"$@\" (git appends the hook args itself)")
    ok(cmd_render(True) == 0, f"render --check: {DIST_INCLUDE_REL} is current")
    with tempfile.TemporaryDirectory() as td:
        f = Path(td) / "x.inc"
        f.write_text(inc, encoding="utf-8")
        e = _clean_env({"PATH": os.environ.get("PATH", "/usr/bin:/bin"), "HOME": td, "GIT_CONFIG_NOSYSTEM": "1"})
        try:
            r = subprocess.run(["git", "config", "--file", str(f), "--show-scope", "--show-origin", "-z",
                                "--get-regexp", r"^hook\."], env=e, capture_output=True, timeout=GIT_TIMEOUT_S)
            ents = parse_listing(r.stdout)
            eff = effective(ents)
            ok(all(eff.get(nm, {}).get("command") == lane_command(ev) for nm, ev in LANES),
               "render: git reads back every command byte-for-byte (';' and '\"' quoted)")
            ok(all(eff[nm]["events"] == [ev] and eff[nm]["enabled"] for nm, ev in LANES),
               "render: git reads back one event per lane, enabled")
        except (OSError, subprocess.SubprocessError) as exc:
            ok(False, f"git config readback ran ({exc})")
    home = Path("/h")
    good = [{"scope": "global", "origin": f"file:{home / INSTALL_INCLUDE_REL}", "key": f"hook.{nm}.{k}", "value": v}
            for nm, ev in LANES for k, v in (("command", lane_command(ev)), ("event", ev), ("enabled", "true"))]
    ok(findings_for(good, home=home, where="t") == [], "audit: the rendered include alone has no findings")
    loc = {"scope": "local", "origin": "file:.git/config"}
    for label, extra, needle in (
            ("repo-local last-one-wins command", {"key": "hook.ws-lane-pre-commit.command", "value": "true"},
             "command replaced"),
            ("repo-local empty event= entry", {"key": "hook.ws-lane-pre-push.event", "value": ""},
             "event cleared"),
            ("repo-local enabled=false", {"key": "hook.ws-lane-commit-msg.enabled", "value": "false"}, "disabled"),
            ("an extra event on a lane", {"key": "hook.ws-lane-pre-commit.event", "value": "pre-push"},
             "extra events"),
            ("a foreign hook under the reserved prefix", {"key": "hook.ws-lane-x.command", "value": "true"},
             "reserved"),
    ):
        got = findings_for(good + [dict(loc, **extra)], home=home, where="t")
        ok(any(needle in g for g in got), f"audit: {label} is a finding ({got})")
    ok(any("missing" in g for g in findings_for(good[3:], home=home, where="t")), "audit: a missing lane is a finding")
    ok(_bool(None) and _bool("yes") and not _bool("false"), "audit: git boolean parsing")
    ok(parse_listing(b"global\0file:/x\0hook.a.event\n\0local\0file:.git/config\0hook.a.enabled\0") ==
       [{"scope": "global", "origin": "file:/x", "key": "hook.a.event", "value": ""},
        {"scope": "local", "origin": "file:.git/config", "key": "hook.a.enabled", "value": None}],
       "audit: -z listing parse (empty value vs no value)")
    # run_hook mapping: block → 1 with the rule; exception / timeout → 0 with a notice.
    import io
    for label, fn, want, needle in (
            ("block exits 1 with the rule", lambda *_a: {"decision": "block", "rule": "I1", "reason": "x",
                                                        "notices": []}, 1, "[I1]"),
            ("allow exits 0", lambda *_a: {"decision": "allow", "notices": ["n"]}, 0, "n"),
            ("an exception allows with a notice", lambda *_a: 1 / 0, 0, "lane error"),
    ):
        err = io.StringIO()
        rc = run_hook("pre-commit", [], [], err=err, decide=fn)
        ok(rc == want and needle in err.getvalue(), f"run_hook: {label} (rc={rc} {err.getvalue()!r})")
    err = io.StringIO()
    rc = run_hook("pre-commit", [], [], err=err, decide=lambda *_a: __import__("time").sleep(2), budget=0.2)
    ok(rc == 0 and "timed out" in err.getvalue(), "run_hook: a timeout allows with a notice")
    helper = TOOLS / "fixtures" / "git_lanes" / "lane_cases.py"
    if not helper.is_file():
        print("self-test SKIP: git-lane fixtures absent (a pinned copy) — not a pass", file=sys.stderr)
        skips.append("fixtures absent")
    else:
        spec = importlib.util.spec_from_file_location("ws_lane_cases", helper)
        mod = importlib.util.module_from_spec(spec)
        assert spec and spec.loader
        spec.loader.exec_module(mod)
        for name, passed, detail in mod.run_all():
            if passed is None:
                print(f"self-test SKIP: {name} ({detail}) — not a pass", file=sys.stderr)
                skips.append(name)
                continue
            ok(passed, f"{name}: {detail}")
        for line in getattr(mod, "REPORT", []):
            print(f"git_lanes self-test info: {line}")
    print(f"git_lanes self-test: {n[0] - len(fails)}/{n[0]} passed, {len(skips)} skipped")
    if fails:
        return 1
    return 3 if skips else 0


if __name__ == "__main__":
    sys.exit(main())
